name = "pokopia-scene-editor"
main = "src/index.ts"
workers_dev = false
compatibility_date = "2026-05-26"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "scene-editor.pokokit.com/api/v1"
zone_name = "pokokit.com"

[[routes]]
pattern = "scene-editor.pokokit.com/api/v1/*"
zone_name = "pokokit.com"

[assets]
directory = "../web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/v1", "/api/v1/*"]
