// Generated from pokopia-color-pattern/docs/pokopia_image_sources/pokopiadex_pokemon_preferences.json.
// Do not edit individual entries by hand; regenerate when source preference data changes.

export const sourcePokemonPreferences = [
  {"key":"abra","preferenceTerms":["dry flavors","metal stuff","soft stuff","strange stuff","watching stuff","wobbly stuff"]},
  {"key":"absol","preferenceTerms":["complicated stuff","dry flavors","exercise","letters and words","nice breezes","soft stuff"]},
  {"key":"aerodactyl","preferenceTerms":["hard stuff","nice breezes","shiny stuff","sour flavors","spinning stuff","stone stuff"]},
  {"key":"alakazam","preferenceTerms":["bitter flavors","letters and words","metal stuff","strange stuff","watching stuff","wobbly stuff"]},
  {"key":"altaria","preferenceTerms":["cute stuff","nice breezes","noisy stuff","soft stuff","sour flavors","watching stuff"]},
  {"key":"amaura","preferenceTerms":["containers","dry flavors","group activities","hard stuff","shiny stuff","stone stuff"]},
  {"key":"ampharos","preferenceTerms":["cute stuff","electronics","glass stuff","pretty flowers","shiny stuff","sour flavors"]},
  {"key":"arbok","preferenceTerms":["garbage","lots of nature","slender objects","spicy flavors","spinning stuff","watching stuff"]},
  {"key":"arcanine","preferenceTerms":["lots of fire","nice breezes","spicy flavors","stone stuff","symbols","watching stuff"]},
  {"key":"ariados","preferenceTerms":["colorful stuff","garbage","lots of nature","rides","sour flavors","wooden stuff"]},
  {"key":"armarouge","preferenceTerms":["exercise","lots of fire","luxury","spicy flavors","stone stuff","strange stuff"]},
  {"key":"articuno","preferenceTerms":["lots of water","luxury","nice breezes","shiny stuff","sour flavors","symbols"]},
  {"key":"audino","preferenceTerms":["bitter flavors","cute stuff","fabric","healing","round stuff","soft stuff"]},
  {"key":"aurorus","preferenceTerms":["hard stuff","noisy stuff","shiny stuff","sour flavors","stone stuff","symbols"]},
  {"key":"axew","preferenceTerms":["hard stuff","lots of dirt","lots of fire","luxury","sharp stuff","sweet flavors"]},
  {"key":"azumarill","preferenceTerms":["construction","cute stuff","lots of water","sour flavors","symbols","wobbly stuff"]},
  {"key":"azurill","preferenceTerms":["cleanliness","cute stuff","healing","lots of water","rides","sour flavors"]},
  {"key":"bastiodon","preferenceTerms":["bitter flavors","exercise","hard stuff","luxury","metal stuff","stone stuff"]},
  {"key":"beldum","preferenceTerms":["complicated stuff","hard stuff","metal stuff","sour flavors","stone stuff","strange stuff"]},
  {"key":"bellossom","preferenceTerms":["cute stuff","lots of nature","noisy stuff","play spaces","pretty flowers","sour flavors"]},
  {"key":"bellsprout","preferenceTerms":["dry flavors","lots of dirt","lots of nature","lots of water","pretty flowers","wooden stuff"]},
  {"key":"blastoise","preferenceTerms":["cleanliness","exercise","healing","lots of water","luxury","sour flavors"]},
  {"key":"blaziken","preferenceTerms":["construction","containers","exercise","lots of fire","luxury","spicy flavors"]},
  {"key":"blissey","preferenceTerms":["fabric","group activities","healing","round stuff","soft stuff","sour flavors"]},
  {"key":"bonsly","preferenceTerms":["hard stuff","lots of nature","round stuff","sour flavors","stone stuff","wooden stuff"]},
  {"key":"bulbasaur","preferenceTerms":["cute stuff","group activities","lots of nature","lots of water","soft stuff","sweet flavors"]},
  {"key":"cacnea","preferenceTerms":["cute stuff","lots of nature","pretty flowers","round stuff","sharp stuff","spicy flavors"]},
  {"key":"cacturne","preferenceTerms":["dry flavors","lots of nature","luxury","nice breezes","sharp stuff","shiny stuff"]},
  {"key":"carkol","preferenceTerms":["hard stuff","lots of fire","metal stuff","rides","spicy flavors","stone stuff"]},
  {"key":"ceruledge","preferenceTerms":["bitter flavors","lots of fire","luxury","spooky stuff","stone stuff","strange stuff"]},
  {"key":"chandelure","preferenceTerms":["dry flavors","lots of fire","spooky stuff","strange stuff","watching stuff","wobbly stuff"]},
  {"key":"chansey","preferenceTerms":["fabric","group activities","healing","round stuff","soft stuff","sweet flavors"]},
  {"key":"charcadet","preferenceTerms":["exercise","lots of fire","luxury","stone stuff","strange stuff","sweet flavors"]},
  {"key":"charizard","preferenceTerms":["exercise","lots of fire","luxury","nice breezes","spicy flavors","wooden stuff"]},
  {"key":"charjabug","preferenceTerms":["bitter flavors","blocky stuff","electronics","glass stuff","lots of nature","watching stuff"]},
  {"key":"charmander","preferenceTerms":["exercise","group activities","hard stuff","lots of fire","spicy flavors","wooden stuff"]},
  {"key":"charmeleon","preferenceTerms":["exercise","hard stuff","lots of fire","rides","spicy flavors","wooden stuff"]},
  {"key":"chatot","preferenceTerms":["fabric","nice breezes","noisy stuff","play spaces","slender objects","sweet flavors"]},
  {"key":"chef-dente","preferenceTerms":["group activities","looks like food","luxury","metal stuff","soft stuff","sweet flavors"]},
  {"key":"cinccino","preferenceTerms":["cleanliness","cute stuff","fabric","rides","soft stuff","sour flavors"]},
  {"key":"cinderace","preferenceTerms":["group activities","lots of fire","play spaces","round stuff","spicy flavors","stone stuff"]},
  {"key":"clefable","preferenceTerms":["cute stuff","group activities","healing","play spaces","pretty flowers","sour flavors"]},
  {"key":"clefairy","preferenceTerms":["cute stuff","group activities","healing","play spaces","pretty flowers","sweet flavors"]},
  {"key":"cleffa","preferenceTerms":["colorful stuff","cute stuff","healing","rides","round stuff","sweet flavors"]},
  {"key":"clodsire","preferenceTerms":["bitter flavors","cleanliness","garbage","lots of dirt","lots of water","round stuff"]},
  {"key":"coalossal","preferenceTerms":["hard stuff","lots of fire","metal stuff","rides","spicy flavors","stone stuff"]},
  {"key":"combee","preferenceTerms":["gatherings","group activities","lots of nature","nice breezes","sweet flavors","wooden stuff"]},
  {"key":"combusken","preferenceTerms":["construction","containers","exercise","lots of fire","spicy flavors","stone stuff"]},
  {"key":"conkeldurr","preferenceTerms":["construction","exercise","group activities","slender objects","spicy flavors","stone stuff"]},
  {"key":"corviknight","preferenceTerms":["bitter flavors","containers","metal stuff","nice breezes","shiny stuff","wooden stuff"]},
  {"key":"corvisquire","preferenceTerms":["containers","dry flavors","nice breezes","shiny stuff","slender objects","wooden stuff"]},
  {"key":"cramorant","preferenceTerms":["bitter flavors","looks like food","lots of water","nice breezes","ocean vibes","slender objects"]},
  {"key":"cranidos","preferenceTerms":["exercise","group activities","hard stuff","spicy flavors","stone stuff","wobbly stuff"]},
  {"key":"crobat","preferenceTerms":["dry flavors","garbage","nice breezes","spooky stuff","watching stuff","wooden stuff"]},
  {"key":"cubone","preferenceTerms":["bitter flavors","construction","exercise","group activities","lots of dirt","slender objects"]},
  {"key":"cyndaquil","preferenceTerms":["fabric","lots of fire","metal stuff","rides","slender objects","sweet flavors"]},
  {"key":"dachsbun","preferenceTerms":["cute stuff","group activities","looks like food","lots of fire","sour flavors","watching stuff"]},
  {"key":"dartrix","preferenceTerms":["cleanliness","lots of nature","nice breezes","slender objects","sour flavors","wooden stuff"]},
  {"key":"decidueye","preferenceTerms":["dry flavors","letters and words","lots of nature","nice breezes","spooky stuff","wooden stuff"]},
  {"key":"dedenne","preferenceTerms":["cute stuff","electronics","group activities","looks like food","sweet flavors","watching stuff"]},
  {"key":"diglett","preferenceTerms":["bitter flavors","cute stuff","group activities","lots of dirt","play spaces","slender objects"]},
  {"key":"ditto","preferenceTerms":[]},
  {"key":"dj-rotom","preferenceTerms":["bitter flavors","blocky stuff","glass stuff","group activities","noisy stuff","shiny stuff"]},
  {"key":"dragapult","preferenceTerms":["group activities","lots of fire","rides","spicy flavors","spooky stuff","strange stuff"]},
  {"key":"dragonair","preferenceTerms":["cleanliness","glass stuff","lots of fire","lots of water","slender objects","sweet flavors"]},
  {"key":"dragonite","preferenceTerms":["cleanliness","dry flavors","lots of fire","nice breezes","pretty flowers","symbols"]},
  {"key":"drakloak","preferenceTerms":["group activities","lots of fire","rides","spooky stuff","strange stuff","sweet flavors"]},
  {"key":"dratini","preferenceTerms":["cleanliness","cute stuff","lots of fire","lots of water","slender objects","sweet flavors"]},
  {"key":"dreepy","preferenceTerms":["group activities","lots of fire","rides","spicy flavors","spooky stuff","strange stuff"]},
  {"key":"drifblim","preferenceTerms":["bitter flavors","nice breezes","spinning stuff","spooky stuff","strange stuff","wobbly stuff"]},
  {"key":"drifloon","preferenceTerms":["bitter flavors","cute stuff","nice breezes","round stuff","spooky stuff","strange stuff"]},
  {"key":"drilbur","preferenceTerms":["lots of dirt","lots of nature","sharp stuff","sour flavors","stone stuff","watching stuff"]},
  {"key":"dugtrio","preferenceTerms":["gatherings","group activities","lots of dirt","play spaces","slender objects","spicy flavors"]},
  {"key":"dusclops","preferenceTerms":["containers","rides","soft stuff","sour flavors","spooky stuff","strange stuff"]},
  {"key":"dusknoir","preferenceTerms":["bitter flavors","containers","group activities","rides","spooky stuff","strange stuff"]},
  {"key":"duskull","preferenceTerms":["bitter flavors","fabric","glass stuff","rides","spooky stuff","strange stuff"]},
  {"key":"eevee","preferenceTerms":["cute stuff","group activities","letters and words","soft stuff","stone stuff","sweet flavors"]},
  {"key":"ekans","preferenceTerms":["garbage","lots of nature","slender objects","spicy flavors","spinning stuff","watching stuff"]},
  {"key":"electabuzz","preferenceTerms":["electronics","exercise","glass stuff","lots of fire","sharp stuff","spicy flavors"]},
  {"key":"electivire","preferenceTerms":["electronics","exercise","glass stuff","hard stuff","lots of fire","sour flavors"]},
  {"key":"electrode","preferenceTerms":["electronics","play spaces","round stuff","shiny stuff","sour flavors","spinning stuff"]},
  {"key":"elekid","preferenceTerms":["cute stuff","electronics","glass stuff","round stuff","spinning stuff","sweet flavors"]},
  {"key":"empoleon","preferenceTerms":["bitter flavors","cleanliness","letters and words","lots of water","metal stuff","ocean vibes"]},
  {"key":"entei","preferenceTerms":["bitter flavors","exercise","lots of fire","luxury","stone stuff","symbols"]},
  {"key":"espeon","preferenceTerms":["complicated stuff","cute stuff","nice breezes","strange stuff","sweet flavors","watching stuff"]},
  {"key":"excadrill","preferenceTerms":["exercise","lots of dirt","metal stuff","sharp stuff","sour flavors","watching stuff"]},
  {"key":"exeggcute","preferenceTerms":["gatherings","group activities","lots of nature","spicy flavors","strange stuff","watching stuff"]},
  {"key":"exeggutor","preferenceTerms":["dry flavors","gatherings","lots of nature","strange stuff","watching stuff","wooden stuff"]},
  {"key":"farfetchd","preferenceTerms":["exercise","nice breezes","slender objects","soft stuff","spicy flavors","wooden stuff"]},
  {"key":"farigiraf","preferenceTerms":["rides","slender objects","soft stuff","sour flavors","strange stuff","watching stuff"]},
  {"key":"fidough","preferenceTerms":["cute stuff","letters and words","lots of fire","soft stuff","sweet flavors","watching stuff"]},
  {"key":"flaaffy","preferenceTerms":["bitter flavors","cute stuff","electronics","glass stuff","rides","shiny stuff"]},
  {"key":"flareon","preferenceTerms":["cute stuff","lots of fire","metal stuff","rides","spicy flavors","wooden stuff"]},
  {"key":"floragato","preferenceTerms":["colorful stuff","cute stuff","lots of nature","pretty flowers","sharp stuff","sour flavors"]},
  {"key":"flygon","preferenceTerms":["lots of dirt","lots of fire","lots of nature","sour flavors","stone stuff","wooden stuff"]},
  {"key":"fraxure","preferenceTerms":["exercise","lots of dirt","lots of fire","luxury","sharp stuff","spicy flavors"]},
  {"key":"froakie","preferenceTerms":["cleanliness","containers","lots of water","ocean vibes","spicy flavors","watching stuff"]},
  {"key":"frogadier","preferenceTerms":["cleanliness","exercise","lots of water","ocean vibes","spicy flavors","watching stuff"]},
  {"key":"gallade","preferenceTerms":["construction","exercise","fabric","healing","spicy flavors","strange stuff"]},
  {"key":"garbodor","preferenceTerms":["complicated stuff","containers","garbage","gatherings","shiny stuff","sour flavors"]},
  {"key":"gardevoir","preferenceTerms":["healing","luxury","sour flavors","strange stuff","symbols","watching stuff"]},
  {"key":"gastly","preferenceTerms":["containers","garbage","group activities","spicy flavors","spooky stuff","strange stuff"]},
  {"key":"gastrodon-east-sea","preferenceTerms":["cleanliness","containers","dry flavors","lots of dirt","lots of water","ocean vibes"]},
  {"key":"gastrodon-west-sea","preferenceTerms":["cleanliness","containers","lots of dirt","lots of water","ocean vibes","sour flavors"]},
  {"key":"gengar","preferenceTerms":["garbage","group activities","rides","spooky stuff","strange stuff","sweet flavors"]},
  {"key":"geodude","preferenceTerms":["dry flavors","exercise","hard stuff","round stuff","spinning stuff","stone stuff"]},
  {"key":"gholdengo","preferenceTerms":["complicated stuff","dry flavors","metal stuff","shiny stuff","spooky stuff","strange stuff"]},
  {"key":"gimmighoul","preferenceTerms":["bitter flavors","complicated stuff","metal stuff","shiny stuff","spooky stuff","strange stuff"]},
  {"key":"girafarig","preferenceTerms":["rides","slender objects","soft stuff","sour flavors","strange stuff","watching stuff"]},
  {"key":"glaceon","preferenceTerms":["cute stuff","glass stuff","group activities","lots of water","shiny stuff","sweet flavors"]},
  {"key":"glimmet","preferenceTerms":["bitter flavors","complicated stuff","garbage","hard stuff","shiny stuff","stone stuff"]},
  {"key":"glimmora","preferenceTerms":["bitter flavors","complicated stuff","garbage","hard stuff","shiny stuff","stone stuff"]},
  {"key":"gloom","preferenceTerms":["dry flavors","garbage","lots of dirt","lots of nature","pretty flowers","soft stuff"]},
  {"key":"golbat","preferenceTerms":["complicated stuff","nice breezes","noisy stuff","spicy flavors","spooky stuff","wooden stuff"]},
  {"key":"golduck","preferenceTerms":["complicated stuff","dry flavors","lots of water","ocean vibes","sharp stuff","strange stuff"]},
  {"key":"golem","preferenceTerms":["exercise","hard stuff","round stuff","sour flavors","spinning stuff","stone stuff"]},
  {"key":"goodra","preferenceTerms":["cleanliness","exercise","healing","lots of water","luxury","sour flavors"]},
  {"key":"goomy","preferenceTerms":["cleanliness","healing","lots of nature","lots of water","luxury","sweet flavors"]},
  {"key":"graveler","preferenceTerms":["bitter flavors","exercise","hard stuff","round stuff","spinning stuff","stone stuff"]},
  {"key":"greedent","preferenceTerms":["group activities","looks like food","luxury","metal stuff","soft stuff","sweet flavors"]},
  {"key":"greninja","preferenceTerms":["bitter flavors","cleanliness","exercise","lots of water","ocean vibes","shiny stuff"]},
  {"key":"grimer","preferenceTerms":["bitter flavors","containers","garbage","gatherings","shiny stuff","spooky stuff"]},
  {"key":"growlithe","preferenceTerms":["letters and words","lots of fire","nice breezes","pretty flowers","stone stuff","sweet flavors"]},
  {"key":"grubbin","preferenceTerms":["containers","dry flavors","electronics","lots of dirt","lots of nature","watching stuff"]},
  {"key":"gulpin","preferenceTerms":["colorful stuff","containers","cute stuff","looks like food","round stuff","spicy flavors"]},
  {"key":"gurdurr","preferenceTerms":["construction","exercise","group activities","metal stuff","slender objects","spicy flavors"]},
  {"key":"gyarados","preferenceTerms":["cleanliness","lots of water","nice breezes","ocean vibes","slender objects","spicy flavors"]},
  {"key":"happiny","preferenceTerms":["containers","fabric","healing","round stuff","soft stuff","sweet flavors"]},
  {"key":"hariyama","preferenceTerms":["construction","exercise","fabric","rides","round stuff","spicy flavors"]},
  {"key":"haunter","preferenceTerms":["garbage","group activities","spicy flavors","spooky stuff","strange stuff","wobbly stuff"]},
  {"key":"haxorus","preferenceTerms":["exercise","lots of dirt","lots of fire","luxury","sharp stuff","sour flavors"]},
  {"key":"heracross","preferenceTerms":["exercise","looks like food","lots of nature","pretty flowers","sweet flavors","wooden stuff"]},
  {"key":"hitmonchan","preferenceTerms":["exercise","fabric","group activities","round stuff","stone stuff","sweet flavors"]},
  {"key":"hitmonlee","preferenceTerms":["exercise","fabric","group activities","round stuff","spicy flavors","stone stuff"]},
  {"key":"hitmontop","preferenceTerms":["exercise","fabric","group activities","round stuff","stone stuff","sweet flavors"]},
  {"key":"ho-oh","preferenceTerms":["lots of fire","lots of nature","nice breezes","spicy flavors","symbols","wooden stuff"]},
  {"key":"honchkrow","preferenceTerms":["bitter flavors","glass stuff","letters and words","nice breezes","shiny stuff","spooky stuff"]},
  {"key":"hoothoot","preferenceTerms":["dry flavors","fabric","nice breezes","soft stuff","watching stuff","wobbly stuff"]},
  {"key":"igglybuff","preferenceTerms":["cute stuff","healing","noisy stuff","play spaces","soft stuff","sweet flavors"]},
  {"key":"illumise","preferenceTerms":["cute stuff","group activities","lots of nature","shiny stuff","sour flavors","wooden stuff"]},
  {"key":"ivysaur","preferenceTerms":["colorful stuff","cute stuff","lots of nature","pretty flowers","soft stuff","sour flavors"]},
  {"key":"jigglypuff","preferenceTerms":["cute stuff","healing","play spaces","soft stuff","sweet flavors","wobbly stuff"]},
  {"key":"jolteon","preferenceTerms":["cute stuff","electronics","glass stuff","sharp stuff","shiny stuff","spicy flavors"]},
  {"key":"kadabra","preferenceTerms":["containers","dry flavors","metal stuff","strange stuff","watching stuff","wobbly stuff"]},
  {"key":"kilowattrel","preferenceTerms":["dry flavors","electronics","gatherings","nice breezes","ocean vibes","slender objects"]},
  {"key":"kirlia","preferenceTerms":["cute stuff","healing","strange stuff","sweet flavors","symbols","watching stuff"]},
  {"key":"koffing","preferenceTerms":["bitter flavors","complicated stuff","garbage","gatherings","soft stuff","wobbly stuff"]},
  {"key":"kricketot","preferenceTerms":["bitter flavors","colorful stuff","lots of nature","noisy stuff","watching stuff","wooden stuff"]},
  {"key":"kricketune","preferenceTerms":["colorful stuff","lots of nature","noisy stuff","spicy flavors","watching stuff","wooden stuff"]},
  {"key":"kyogre","preferenceTerms":["dry flavors","glass stuff","lots of water","luxury","ocean vibes","shiny stuff"]},
  {"key":"lampent","preferenceTerms":["bitter flavors","containers","lots of fire","spooky stuff","strange stuff","wobbly stuff"]},
  {"key":"lapras","preferenceTerms":["cleanliness","healing","lots of water","ocean vibes","sour flavors","watching stuff"]},
  {"key":"larvesta","preferenceTerms":["bitter flavors","lots of fire","lots of nature","sharp stuff","symbols","wooden stuff"]},
  {"key":"larvitar","preferenceTerms":["looks like food","lots of dirt","luxury","shiny stuff","stone stuff","sweet flavors"]},
  {"key":"leafeon","preferenceTerms":["cute stuff","fabric","healing","lots of nature","pretty flowers","sour flavors"]},
  {"key":"litwick","preferenceTerms":["bitter flavors","blocky stuff","lots of fire","spooky stuff","strange stuff","wobbly stuff"]},
  {"key":"lombre","preferenceTerms":["bitter flavors","cleanliness","containers","lots of nature","lots of water","noisy stuff"]},
  {"key":"lotad","preferenceTerms":["cleanliness","containers","dry flavors","lots of nature","lots of water","noisy stuff"]},
  {"key":"lucario","preferenceTerms":["complicated stuff","construction","dry flavors","exercise","healing","metal stuff"]},
  {"key":"ludicolo","preferenceTerms":["containers","dry flavors","lots of nature","lots of water","noisy stuff","play spaces"]},
  {"key":"lugia","preferenceTerms":["dry flavors","lots of water","nice breezes","ocean vibes","strange stuff","symbols"]},
  {"key":"machamp","preferenceTerms":["construction","exercise","group activities","hard stuff","spicy flavors","stone stuff"]},
  {"key":"machoke","preferenceTerms":["construction","exercise","group activities","hard stuff","sour flavors","stone stuff"]},
  {"key":"machop","preferenceTerms":["construction","exercise","group activities","hard stuff","spicy flavors","stone stuff"]},
  {"key":"magby","preferenceTerms":["cute stuff","lots of fire","stone stuff","sweet flavors","watching stuff","wobbly stuff"]},
  {"key":"magikarp","preferenceTerms":["group activities","lots of water","ocean vibes","rides","sweet flavors","wobbly stuff"]},
  {"key":"magmar","preferenceTerms":["electronics","exercise","hard stuff","lots of fire","stone stuff","sweet flavors"]},
  {"key":"magmortar","preferenceTerms":["dry flavors","electronics","exercise","hard stuff","lots of fire","stone stuff"]},
  {"key":"magnemite","preferenceTerms":["bitter flavors","electronics","group activities","hard stuff","metal stuff","shiny stuff"]},
  {"key":"magneton","preferenceTerms":["bitter flavors","electronics","gatherings","group activities","metal stuff","shiny stuff"]},
  {"key":"magnezone","preferenceTerms":["bitter flavors","electronics","gatherings","hard stuff","luxury","metal stuff"]},
  {"key":"makuhita","preferenceTerms":["construction","exercise","fabric","round stuff","sweet flavors","wooden stuff"]},
  {"key":"mareep","preferenceTerms":["cute stuff","electronics","fabric","glass stuff","shiny stuff","sweet flavors"]},
  {"key":"marill","preferenceTerms":["cleanliness","cute stuff","lots of water","round stuff","sour flavors","symbols"]},
  {"key":"marowak","preferenceTerms":["construction","dry flavors","exercise","lots of dirt","luxury","slender objects"]},
  {"key":"mawile","preferenceTerms":["colorful stuff","cute stuff","dry flavors","group activities","looks like food","metal stuff"]},
  {"key":"meowscarada","preferenceTerms":["cute stuff","dry flavors","lots of nature","luxury","pretty flowers","shiny stuff"]},
  {"key":"meowth","preferenceTerms":["containers","glass stuff","group activities","luxury","shiny stuff","spicy flavors"]},
  {"key":"metagross","preferenceTerms":["dry flavors","exercise","hard stuff","luxury","metal stuff","strange stuff"]},
  {"key":"metang","preferenceTerms":["bitter flavors","complicated stuff","hard stuff","metal stuff","stone stuff","strange stuff"]},
  {"key":"mew","preferenceTerms":["complicated stuff","luxury","play spaces","strange stuff","sweet flavors","watching stuff"]},
  {"key":"mewtwo","preferenceTerms":["complicated stuff","dry flavors","letters and words","stone stuff","strange stuff","watching stuff"]},
  {"key":"mime-jr","preferenceTerms":["colorful stuff","cute stuff","play spaces","rides","strange stuff","sweet flavors"]},
  {"key":"mimikyu","preferenceTerms":["bitter flavors","cute stuff","electronics","fabric","group activities","spooky stuff"]},
  {"key":"minccino","preferenceTerms":["cleanliness","cute stuff","fabric","rides","soft stuff","sweet flavors"]},
  {"key":"minun","preferenceTerms":["cute stuff","electronics","glass stuff","group activities","soft stuff","spicy flavors"]},
  {"key":"misdreavus","preferenceTerms":["colorful stuff","dry flavors","shiny stuff","spooky stuff","strange stuff","watching stuff"]},
  {"key":"mismagius","preferenceTerms":["bitter flavors","group activities","noisy stuff","spooky stuff","strange stuff","wobbly stuff"]},
  {"key":"moltres","preferenceTerms":["lots of fire","luxury","nice breezes","spicy flavors","stone stuff","symbols"]},
  {"key":"mosslax","preferenceTerms":["fabric","looks like food","soft stuff","spicy flavors","strange stuff","watching stuff"]},
  {"key":"mr-mime","preferenceTerms":["bitter flavors","cute stuff","rides","strange stuff","watching stuff","wobbly stuff"]},
  {"key":"muk","preferenceTerms":["bitter flavors","colorful stuff","garbage","gatherings","shiny stuff","spooky stuff"]},
  {"key":"munchlax","preferenceTerms":["dry flavors","group activities","looks like food","lots of nature","soft stuff","wobbly stuff"]},
  {"key":"murkrow","preferenceTerms":["bitter flavors","fabric","group activities","luxury","nice breezes","shiny stuff"]},
  {"key":"ninetales","preferenceTerms":["dry flavors","lots of fire","luxury","pretty flowers","soft stuff","watching stuff"]},
  {"key":"noctowl","preferenceTerms":["containers","dry flavors","letters and words","nice breezes","soft stuff","watching stuff"]},
  {"key":"noibat","preferenceTerms":["fabric","looks like food","luxury","nice breezes","spicy flavors","watching stuff"]},
  {"key":"noivern","preferenceTerms":["dry flavors","looks like food","lots of fire","nice breezes","play spaces","watching stuff"]},
  {"key":"oddish","preferenceTerms":["bitter flavors","lots of dirt","lots of nature","lots of water","pretty flowers","soft stuff"]},
  {"key":"onix","preferenceTerms":["blocky stuff","dry flavors","exercise","lots of dirt","slender objects","stone stuff"]},
  {"key":"paras","preferenceTerms":["bitter flavors","looks like food","lots of dirt","lots of nature","watching stuff","wooden stuff"]},
  {"key":"parasect","preferenceTerms":["bitter flavors","lots of dirt","lots of nature","strange stuff","watching stuff","wooden stuff"]},
  {"key":"pawmi","preferenceTerms":["cute stuff","electronics","glass stuff","group activities","shiny stuff","sweet flavors"]},
  {"key":"pawmo","preferenceTerms":["electronics","exercise","glass stuff","group activities","shiny stuff","sweet flavors"]},
  {"key":"pawmot","preferenceTerms":["dry flavors","electronics","exercise","group activities","healing","shiny stuff"]},
  {"key":"peakychu","preferenceTerms":["cute stuff","electronics","glass stuff","healing","letters and words","sweet flavors"]},
  {"key":"pelipper","preferenceTerms":["cleanliness","dry flavors","lots of water","nice breezes","ocean vibes","watching stuff"]},
  {"key":"persian","preferenceTerms":["containers","group activities","luxury","shiny stuff","sour flavors","watching stuff"]},
  {"key":"pichu","preferenceTerms":["cute stuff","electronics","fabric","glass stuff","pretty flowers","sweet flavors"]},
  {"key":"pidgeot","preferenceTerms":["lots of nature","luxury","nice breezes","soft stuff","sour flavors","wooden stuff"]},
  {"key":"pidgeotto","preferenceTerms":["looks like food","lots of nature","nice breezes","soft stuff","spicy flavors","watching stuff"]},
  {"key":"pidgey","preferenceTerms":["lots of nature","nice breezes","play spaces","soft stuff","sour flavors","watching stuff"]},
  {"key":"pikachu","preferenceTerms":["electronics","glass stuff","group activities","rides","round stuff","sour flavors"]},
  {"key":"pinsir","preferenceTerms":["exercise","lots of nature","pretty flowers","sharp stuff","spicy flavors","wooden stuff"]},
  {"key":"piplup","preferenceTerms":["cleanliness","containers","lots of water","nice breezes","ocean vibes","sweet flavors"]},
  {"key":"plusle","preferenceTerms":["cute stuff","electronics","glass stuff","group activities","soft stuff","sweet flavors"]},
  {"key":"politoed","preferenceTerms":["gatherings","group activities","lots of water","noisy stuff","play spaces","sour flavors"]},
  {"key":"poliwag","preferenceTerms":["cleanliness","lots of water","rides","round stuff","spinning stuff","sweet flavors"]},
  {"key":"poliwhirl","preferenceTerms":["bitter flavors","cleanliness","exercise","lots of nature","lots of water","spinning stuff"]},
  {"key":"poliwrath","preferenceTerms":["cleanliness","construction","exercise","group activities","lots of water","spicy flavors"]},
  {"key":"porygon","preferenceTerms":["bitter flavors","blocky stuff","colorful stuff","construction","soft stuff","strange stuff"]},
  {"key":"porygon-z","preferenceTerms":["colorful stuff","dry flavors","fabric","soft stuff","strange stuff","watching stuff"]},
  {"key":"porygon2","preferenceTerms":["colorful stuff","construction","round stuff","soft stuff","sour flavors","strange stuff"]},
  {"key":"prinplup","preferenceTerms":["cleanliness","containers","dry flavors","lots of water","nice breezes","ocean vibes"]},
  {"key":"prof-tangrowth","preferenceTerms":["complicated stuff","dry flavors","group activities","letters and words","lots of nature","strange stuff"]},
  {"key":"psyduck","preferenceTerms":["complicated stuff","dry flavors","healing","lots of water","ocean vibes","strange stuff"]},
  {"key":"pupitar","preferenceTerms":["dry flavors","hard stuff","luxury","shiny stuff","stone stuff","watching stuff"]},
  {"key":"quilava","preferenceTerms":["fabric","lots of fire","metal stuff","rides","slender objects","sweet flavors"]},
  {"key":"raboot","preferenceTerms":["containers","dry flavors","group activities","lots of fire","play spaces","stone stuff"]},
  {"key":"raichu","preferenceTerms":["electronics","glass stuff","group activities","play spaces","round stuff","sour flavors"]},
  {"key":"raikou","preferenceTerms":["dry flavors","electronics","glass stuff","luxury","nice breezes","shiny stuff"]},
  {"key":"ralts","preferenceTerms":["cute stuff","healing","strange stuff","sweet flavors","symbols","watching stuff"]},
  {"key":"rampardos","preferenceTerms":["dry flavors","exercise","hard stuff","luxury","metal stuff","stone stuff"]},
  {"key":"riolu","preferenceTerms":["construction","exercise","fabric","gatherings","spicy flavors","watching stuff"]},
  {"key":"rolycoly","preferenceTerms":["hard stuff","lots of fire","metal stuff","rides","sour flavors","stone stuff"]},
  {"key":"rookidee","preferenceTerms":["containers","nice breezes","shiny stuff","slender objects","sour flavors","wooden stuff"]},
  {"key":"rotom","preferenceTerms":["bitter flavors","blocky stuff","glass stuff","group activities","noisy stuff","shiny stuff"]},
  {"key":"rowlet","preferenceTerms":["containers","dry flavors","lots of nature","nice breezes","spinning stuff","wooden stuff"]},
  {"key":"scizor","preferenceTerms":["bitter flavors","exercise","hard stuff","lots of nature","metal stuff","wooden stuff"]},
  {"key":"scorbunny","preferenceTerms":["dry flavors","group activities","lots of fire","sharp stuff","soft stuff","stone stuff"]},
  {"key":"scyther","preferenceTerms":["exercise","lots of nature","nice breezes","sharp stuff","spicy flavors","wooden stuff"]},
  {"key":"serperior","preferenceTerms":["containers","dry flavors","lots of nature","lots of water","slender objects","wooden stuff"]},
  {"key":"servine","preferenceTerms":["bitter flavors","cleanliness","lots of nature","lots of water","shiny stuff","wooden stuff"]},
  {"key":"shellos-east-sea","preferenceTerms":["cleanliness","colorful stuff","containers","dry flavors","lots of water","ocean vibes"]},
  {"key":"shellos-west-sea","preferenceTerms":["cleanliness","colorful stuff","containers","lots of water","ocean vibes","sour flavors"]},
  {"key":"shieldon","preferenceTerms":["hard stuff","luxury","metal stuff","round stuff","stone stuff","sweet flavors"]},
  {"key":"skwovet","preferenceTerms":["dry flavors","looks like food","round stuff","soft stuff","watching stuff","wooden stuff"]},
  {"key":"sliggoo","preferenceTerms":["cleanliness","healing","lots of water","luxury","soft stuff","sweet flavors"]},
  {"key":"slowbro","preferenceTerms":["cleanliness","dry flavors","group activities","healing","lots of water","strange stuff"]},
  {"key":"slowking","preferenceTerms":["cleanliness","group activities","healing","lots of water","sour flavors","strange stuff"]},
  {"key":"slowpoke","preferenceTerms":["cleanliness","dry flavors","healing","lots of water","soft stuff","strange stuff"]},
  {"key":"smeargle","preferenceTerms":["colorful stuff","dry flavors","fabric","shiny stuff","soft stuff","strange stuff"]},
  {"key":"smearguru","preferenceTerms":["colorful stuff","dry flavors","fabric","shiny stuff","soft stuff","strange stuff"]},
  {"key":"snivy","preferenceTerms":["lots of nature","lots of water","shiny stuff","sour flavors","wobbly stuff","wooden stuff"]},
  {"key":"snorlax","preferenceTerms":["dry flavors","fabric","looks like food","rides","soft stuff","wobbly stuff"]},
  {"key":"spinarak","preferenceTerms":["bitter flavors","colorful stuff","garbage","lots of nature","rides","wooden stuff"]},
  {"key":"sprigatito","preferenceTerms":["colorful stuff","containers","cute stuff","lots of nature","pretty flowers","sweet flavors"]},
  {"key":"squirtle","preferenceTerms":["cleanliness","cute stuff","group activities","healing","lots of water","sweet flavors"]},
  {"key":"steelix","preferenceTerms":["hard stuff","lots of dirt","metal stuff","slender objects","sour flavors","stone stuff"]},
  {"key":"sudowoodo","preferenceTerms":["dry flavors","hard stuff","lots of nature","stone stuff","watching stuff","wooden stuff"]},
  {"key":"suicune","preferenceTerms":["cleanliness","healing","lots of water","ocean vibes","sour flavors","watching stuff"]},
  {"key":"swablu","preferenceTerms":["cleanliness","cute stuff","nice breezes","soft stuff","sweet flavors","watching stuff"]},
  {"key":"swalot","preferenceTerms":["bitter flavors","colorful stuff","containers","garbage","looks like food","round stuff"]},
  {"key":"sylveon","preferenceTerms":["cute stuff","fabric","lots of nature","noisy stuff","round stuff","sweet flavors"]},
  {"key":"tangela","preferenceTerms":["gatherings","lots of nature","lots of water","pretty flowers","slender objects","sour flavors"]},
  {"key":"tangrowth","preferenceTerms":["bitter flavors","gatherings","lots of nature","lots of water","pretty flowers","watching stuff"]},
  {"key":"tatsugiri-curly-form","preferenceTerms":["gatherings","group activities","lots of water","ocean vibes","slender objects","sour flavors"]},
  {"key":"tatsugiri-droopy-form","preferenceTerms":["blocky stuff","group activities","lots of water","ocean vibes","spinning stuff","sweet flavors"]},
  {"key":"tatsugiri-stretchy-form","preferenceTerms":["containers","group activities","letters and words","lots of water","ocean vibes","spicy flavors"]},
  {"key":"timburr","preferenceTerms":["blocky stuff","construction","exercise","slender objects","spicy flavors","wooden stuff"]},
  {"key":"tinkatink","preferenceTerms":["construction","cute stuff","exercise","looks like food","metal stuff","sweet flavors"]},
  {"key":"tinkaton","preferenceTerms":["blocky stuff","construction","cute stuff","exercise","metal stuff","spicy flavors"]},
  {"key":"tinkatuff","preferenceTerms":["construction","cute stuff","exercise","group activities","metal stuff","sour flavors"]},
  {"key":"torchic","preferenceTerms":["containers","cute stuff","lots of fire","pretty flowers","stone stuff","sweet flavors"]},
  {"key":"torkoal","preferenceTerms":["dry flavors","hard stuff","lots of fire","metal stuff","stone stuff","watching stuff"]},
  {"key":"toxel","preferenceTerms":["electronics","garbage","glass stuff","noisy stuff","shiny stuff","sweet flavors"]},
  {"key":"toxtricity-amped-form","preferenceTerms":["electronics","noisy stuff","play spaces","sharp stuff","slender objects","spicy flavors"]},
  {"key":"toxtricity-low-key-form","preferenceTerms":["bitter flavors","electronics","noisy stuff","play spaces","sharp stuff","slender objects"]},
  {"key":"trapinch","preferenceTerms":["exercise","hard stuff","lots of dirt","spicy flavors","strange stuff","watching stuff"]},
  {"key":"trubbish","preferenceTerms":["bitter flavors","complicated stuff","containers","garbage","gatherings","shiny stuff"]},
  {"key":"typhlosion","preferenceTerms":["dry flavors","fabric","lots of fire","metal stuff","rides","slender objects"]},
  {"key":"tyranitar","preferenceTerms":["exercise","hard stuff","luxury","shiny stuff","spicy flavors","stone stuff"]},
  {"key":"tyrantrum","preferenceTerms":["exercise","hard stuff","lots of fire","luxury","sour flavors","stone stuff"]},
  {"key":"tyrogue","preferenceTerms":["exercise","fabric","group activities","round stuff","spicy flavors","stone stuff"]},
  {"key":"tyrunt","preferenceTerms":["exercise","hard stuff","lots of fire","luxury","stone stuff","sweet flavors"]},
  {"key":"umbreon","preferenceTerms":["bitter flavors","cute stuff","letters and words","luxury","shiny stuff","watching stuff"]},
  {"key":"vaporeon","preferenceTerms":["cleanliness","cute stuff","lots of water","pretty flowers","sweet flavors","watching stuff"]},
  {"key":"venomoth","preferenceTerms":["bitter flavors","lots of nature","nice breezes","pretty flowers","watching stuff","wooden stuff"]},
  {"key":"venonat","preferenceTerms":["bitter flavors","complicated stuff","letters and words","lots of nature","watching stuff","wooden stuff"]},
  {"key":"venusaur","preferenceTerms":["cute stuff","lots of nature","luxury","pretty flowers","soft stuff","sour flavors"]},
  {"key":"vespiquen","preferenceTerms":["complicated stuff","gatherings","lots of nature","nice breezes","sweet flavors","wooden stuff"]},
  {"key":"vibrava","preferenceTerms":["bitter flavors","lots of dirt","lots of fire","lots of nature","luxury","noisy stuff"]},
  {"key":"victreebel","preferenceTerms":["bitter flavors","colorful stuff","lots of dirt","lots of nature","pretty flowers","wooden stuff"]},
  {"key":"vikavolt","preferenceTerms":["dry flavors","electronics","exercise","glass stuff","lots of nature","nice breezes"]},
  {"key":"vileplume","preferenceTerms":["bitter flavors","colorful stuff","lots of dirt","lots of nature","pretty flowers","soft stuff"]},
  {"key":"volbeat","preferenceTerms":["cute stuff","group activities","lots of nature","shiny stuff","sweet flavors","wooden stuff"]},
  {"key":"volcanion","preferenceTerms":["containers","lots of fire","lots of water","spicy flavors","stone stuff","symbols"]},
  {"key":"volcarona","preferenceTerms":["dry flavors","letters and words","lots of fire","lots of nature","symbols","wooden stuff"]},
  {"key":"voltorb","preferenceTerms":["bitter flavors","colorful stuff","electronics","round stuff","shiny stuff","spinning stuff"]},
  {"key":"vulpix","preferenceTerms":["bitter flavors","cute stuff","lots of fire","pretty flowers","round stuff","soft stuff"]},
  {"key":"wartortle","preferenceTerms":["cleanliness","exercise","hard stuff","healing","lots of water","spicy flavors"]},
  {"key":"wattrel","preferenceTerms":["complicated stuff","electronics","gatherings","nice breezes","ocean vibes","spicy flavors"]},
  {"key":"weepinbell","preferenceTerms":["bitter flavors","colorful stuff","lots of dirt","lots of nature","pretty flowers","wooden stuff"]},
  {"key":"weezing","preferenceTerms":["bitter flavors","complicated stuff","garbage","gatherings","soft stuff","wobbly stuff"]},
  {"key":"wigglytuff","preferenceTerms":["cute stuff","group activities","healing","play spaces","soft stuff","sour flavors"]},
  {"key":"wingull","preferenceTerms":["cleanliness","dry flavors","lots of water","nice breezes","ocean vibes","watching stuff"]},
  {"key":"wooper","preferenceTerms":["cleanliness","garbage","group activities","lots of dirt","sour flavors","stone stuff"]},
  {"key":"zapdos","preferenceTerms":["electronics","glass stuff","luxury","nice breezes","spicy flavors","symbols"]},
  {"key":"zoroark","preferenceTerms":["glass stuff","group activities","luxury","shiny stuff","spicy flavors","strange stuff"]},
  {"key":"zorua","preferenceTerms":["cute stuff","glass stuff","group activities","luxury","shiny stuff","sour flavors"]},
  {"key":"zubat","preferenceTerms":["complicated stuff","nice breezes","noisy stuff","spicy flavors","spooky stuff","wooden stuff"]},
] as const;

export const sourceItemPreferenceTerms = [
  {"slug":"adrenaline-orb","preferenceTerms":["round stuff"]},
  {"slug":"aether-paradise","preferenceTerms":["round stuff"]},
  {"slug":"afternoon-tea-set","preferenceTerms":["colorful stuff","gatherings","looks like food","luxury"]},
  {"slug":"air-conditioner","preferenceTerms":["electronics","metal stuff","nice breezes","strange stuff"]},
  {"slug":"alarm-clock","preferenceTerms":["glass stuff","metal stuff","noisy stuff","round stuff","strange stuff"]},
  {"slug":"antique-bed","preferenceTerms":["fabric","group activities","luxury","soft stuff"]},
  {"slug":"antique-chair","preferenceTerms":["colorful stuff","fabric","luxury","soft stuff"]},
  {"slug":"antique-chandelier","preferenceTerms":["electronics","glass stuff","luxury","metal stuff"]},
  {"slug":"antique-chest","preferenceTerms":["blocky stuff","containers","luxury","wooden stuff"]},
  {"slug":"antique-clock","preferenceTerms":["complicated stuff","glass stuff","luxury","wooden stuff"]},
  {"slug":"antique-closet","preferenceTerms":["blocky stuff","containers","luxury","wooden stuff"]},
  {"slug":"antique-dresser","preferenceTerms":["glass stuff","luxury"]},
  {"slug":"antique-sofa","preferenceTerms":["colorful stuff","fabric","group activities","luxury","soft stuff"]},
  {"slug":"antique-table","preferenceTerms":["luxury","wooden stuff"]},
  {"slug":"arcade-machine","preferenceTerms":["blocky stuff","electronics","glass stuff","group activities","play spaces"]},
  {"slug":"arcanine-doll","preferenceTerms":["cute stuff","fabric"]},
  {"slug":"area-zero","preferenceTerms":["round stuff"]},
  {"slug":"armor-fossil","preferenceTerms":["hard stuff","lots of dirt","luxury","round stuff","strange stuff"]},
  {"slug":"armor-fragment","preferenceTerms":["strange stuff"]},
  {"slug":"arrow-sign","preferenceTerms":["letters and words","wooden stuff"]},
  {"slug":"audio-mixer","preferenceTerms":["complicated stuff","electronics","strange stuff"]},
  {"slug":"auspicious-armor","preferenceTerms":["luxury","shiny stuff","strange stuff"]},
  {"slug":"balloons","preferenceTerms":["colorful stuff","gatherings","play spaces","round stuff","wobbly stuff"]},
  {"slug":"barrel","preferenceTerms":["containers","metal stuff","round stuff","wooden stuff"]},
  {"slug":"bathtime-set","preferenceTerms":["cleanliness","cute stuff","lots of water","shiny stuff"]},
  {"slug":"bathtub","preferenceTerms":["cleanliness","lots of water","stone stuff","strange stuff"]},
  {"slug":"battle-gym-leader-1","preferenceTerms":["round stuff"]},
  {"slug":"battle-gym-leader-2","preferenceTerms":["round stuff"]},
  {"slug":"battle-gym-leader-battle","preferenceTerms":["round stuff"]},
  {"slug":"beach-chair","preferenceTerms":["fabric","ocean vibes","soft stuff"]},
  {"slug":"beach-parasol","preferenceTerms":["fabric","lots of water","ocean vibes"]},
  {"slug":"beautiful-flower","preferenceTerms":["pretty flowers"]},
  {"slug":"bell","preferenceTerms":["luxury","metal stuff","shiny stuff","strange stuff","wobbly stuff"]},
  {"slug":"bell-tower","preferenceTerms":["round stuff"]},
  {"slug":"berry-basket","preferenceTerms":["blocky stuff","containers","looks like food","lots of nature"]},
  {"slug":"berry-bed","preferenceTerms":["cute stuff","fabric","looks like food","lots of nature","soft stuff"]},
  {"slug":"berry-case","preferenceTerms":["containers","cute stuff","looks like food","lots of nature"]},
  {"slug":"berry-chair","preferenceTerms":["cute stuff","looks like food","lots of nature","soft stuff"]},
  {"slug":"berry-clock","preferenceTerms":["cute stuff","fabric","looks like food","lots of nature","round stuff","wobbly stuff"]},
  {"slug":"berry-hanging-lamp","preferenceTerms":["cute stuff","electronics","glass stuff","looks like food","lots of nature","slender objects"]},
  {"slug":"berry-print","preferenceTerms":["looks like food","lots of nature"]},
  {"slug":"berry-print-interior","preferenceTerms":["looks like food","lots of nature"]},
  {"slug":"berry-table","preferenceTerms":["looks like food","lots of nature"]},
  {"slug":"berry-table-lamp","preferenceTerms":["cute stuff","electronics","glass stuff","looks like food","lots of nature"]},
  {"slug":"berry-wall-decoration","preferenceTerms":["colorful stuff","gatherings","looks like food","lots of nature","watching stuff"]},
  {"slug":"big-drum","preferenceTerms":["round stuff","wobbly stuff"]},
  {"slug":"big-nugget","preferenceTerms":["metal stuff","round stuff","shiny stuff","stone stuff"]},
  {"slug":"big-root","preferenceTerms":["lots of nature"]},
  {"slug":"big-storage-box","preferenceTerms":["wooden stuff"]},
  {"slug":"bike","preferenceTerms":["complicated stuff","exercise","metal stuff","rides","strange stuff"]},
  {"slug":"black-paint","preferenceTerms":["colorful stuff","lots of dirt"]},
  {"slug":"blank-canvas","preferenceTerms":["fabric","watching stuff"]},
  {"slug":"blue-meteor-lamp","preferenceTerms":["cute stuff","electronics","glass stuff","shiny stuff"]},
  {"slug":"blue-paint","preferenceTerms":["colorful stuff","lots of dirt"]},
  {"slug":"bonfire","preferenceTerms":["group activities","lots of fire","watching stuff"]},
  {"slug":"boo-in-the-box","preferenceTerms":["blocky stuff","containers","group activities","play spaces","spooky stuff","strange stuff"]},
  {"slug":"book","preferenceTerms":["blocky stuff","complicated stuff","letters and words","watching stuff"]},
  {"slug":"bookcase","preferenceTerms":["blocky stuff","colorful stuff","containers","watching stuff","wooden stuff"]},
  {"slug":"bouncy-blue-bathtub","preferenceTerms":["cleanliness","cute stuff","lots of water","strange stuff"]},
  {"slug":"boutique","preferenceTerms":["round stuff"]},
  {"slug":"box-sofa","preferenceTerms":["blocky stuff","fabric","soft stuff"]},
  {"slug":"campfire","preferenceTerms":["group activities","lots of fire","stone stuff"]},
  {"slug":"cannon","preferenceTerms":["lots of fire","metal stuff","strange stuff"]},
  {"slug":"canoe","preferenceTerms":["group activities","round stuff"]},
  {"slug":"card-reader","preferenceTerms":["electronics","glass stuff","metal stuff","strange stuff"]},
  {"slug":"cardboard-boxes","preferenceTerms":["blocky stuff","containers","gatherings"]},
  {"slug":"cash-register","preferenceTerms":["complicated stuff","containers","metal stuff","strange stuff"]},
  {"slug":"castform-weather-charm","preferenceTerms":["cute stuff","fabric","spinning stuff","strange stuff"]},
  {"slug":"caves-of-mt-moon","preferenceTerms":["round stuff"]},
  {"slug":"cd-player","preferenceTerms":["electronics","group activities","noisy stuff"]},
  {"slug":"cd-rack","preferenceTerms":["colorful stuff","complicated stuff","containers","gatherings","shiny stuff","strange stuff","watching stuff","wooden stuff"]},
  {"slug":"ceiling-fan","preferenceTerms":["electronics","nice breezes","spinning stuff","strange stuff","wobbly stuff"]},
  {"slug":"cell-phone","preferenceTerms":["blocky stuff","electronics","glass stuff","metal stuff","shiny stuff"]},
  {"slug":"chansey-plant","preferenceTerms":["blocky stuff","cute stuff","luxury","pretty flowers","round stuff"]},
  {"slug":"charcoal","preferenceTerms":["lots of fire"]},
  {"slug":"chic-chair","preferenceTerms":["fabric","luxury","soft stuff"]},
  {"slug":"chic-sofa","preferenceTerms":["fabric","group activities","luxury","soft stuff"]},
  {"slug":"chic-streetlight","preferenceTerms":["electronics","glass stuff","metal stuff","shiny stuff","slender objects"]},
  {"slug":"chic-table","preferenceTerms":["luxury"]},
  {"slug":"chocolate-cookies","preferenceTerms":["colorful stuff","gatherings","looks like food","round stuff"]},
  {"slug":"cleaning-supplies","preferenceTerms":["cleanliness","lots of water","shiny stuff"]},
  {"slug":"clear-amulet","preferenceTerms":["glass stuff","shiny stuff"]},
  {"slug":"clear-bell","preferenceTerms":["noisy stuff","round stuff","shiny stuff","strange stuff"]},
  {"slug":"clefairy-doll","preferenceTerms":["cute stuff","fabric","soft stuff"]},
  {"slug":"computer","preferenceTerms":["complicated stuff","electronics","glass stuff","metal stuff","shiny stuff"]},
  {"slug":"concrete-pipe","preferenceTerms":["round stuff","stone stuff"]},
  {"slug":"construction-supplies","preferenceTerms":["construction","containers","gatherings","group activities","metal stuff","round stuff"]},
  {"slug":"contest-spectacular","preferenceTerms":["round stuff"]},
  {"slug":"control-unit","preferenceTerms":["blocky stuff","complicated stuff"]},
  {"slug":"cooking-stove","preferenceTerms":["blocky stuff","lots of fire","metal stuff","strange stuff"]},
  {"slug":"cool-bass-guitar","preferenceTerms":["electronics","noisy stuff","strange stuff"]},
  {"slug":"cool-electric-guitar","preferenceTerms":["electronics","noisy stuff","strange stuff"]},
  {"slug":"copper-ingot","preferenceTerms":["metal stuff"]},
  {"slug":"copper-ore","preferenceTerms":["metal stuff"]},
  {"slug":"corkboard","preferenceTerms":["blocky stuff","gatherings","watching stuff"]},
  {"slug":"corrugated-metal","preferenceTerms":["metal stuff"]},
  {"slug":"crystal-ball","preferenceTerms":["fabric","glass stuff","round stuff","shiny stuff","strange stuff"]},
  {"slug":"crystal-fragment","preferenceTerms":["glass stuff","shiny stuff"]},
  {"slug":"cute-bed","preferenceTerms":["cute stuff","fabric","soft stuff"]},
  {"slug":"cute-chair","preferenceTerms":["cute stuff","fabric","soft stuff"]},
  {"slug":"cute-dresser","preferenceTerms":["containers","cute stuff","glass stuff","strange stuff"]},
  {"slug":"cute-flower","preferenceTerms":["cute stuff","pretty flowers"]},
  {"slug":"cute-lamp","preferenceTerms":["cute stuff","electronics","glass stuff"]},
  {"slug":"cute-sofa","preferenceTerms":["cute stuff","fabric","group activities","soft stuff"]},
  {"slug":"cute-table","preferenceTerms":["cute stuff"]},
  {"slug":"cutting-board","preferenceTerms":["wooden stuff"]},
  {"slug":"cyan-paint","preferenceTerms":["colorful stuff","lots of dirt"]},
  {"slug":"deck-chair","preferenceTerms":["ocean vibes"]},
  {"slug":"decorative-bookshelf","preferenceTerms":["gatherings","letters and words"]},
  {"slug":"decorative-plant-shelf","preferenceTerms":["gatherings","pretty flowers"]},
  {"slug":"decorative-storage-shelf","preferenceTerms":["gatherings","stone stuff","strange stuff"]},
  {"slug":"desk-light","preferenceTerms":["electronics","glass stuff","metal stuff","slender objects"]},
  {"slug":"despot-fossil-body","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"despot-fossil-head","preferenceTerms":["hard stuff","lots of dirt","luxury","strange stuff"]},
  {"slug":"despot-fossil-legs","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"despot-fossil-tail","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"dining-cabinet","preferenceTerms":["containers","gatherings","glass stuff","luxury","wooden stuff"]},
  {"slug":"ditto-doll","preferenceTerms":["cute stuff","fabric","soft stuff"]},
  {"slug":"ditto-flag","preferenceTerms":["stone stuff"]},
  {"slug":"double-streetlight","preferenceTerms":["electronics","glass stuff","metal stuff","slender objects"]},
  {"slug":"dragonite-doll","preferenceTerms":["cute stuff","fabric","soft stuff"]},
  {"slug":"dress-up-with-props","preferenceTerms":["round stuff"]},
  {"slug":"driftveil-city","preferenceTerms":["round stuff"]},
  {"slug":"ecruteak-city","preferenceTerms":["round stuff"]},
  {"slug":"eerie-candle","preferenceTerms":["cute stuff","lots of fire","spooky stuff","stone stuff"]},
  {"slug":"eevee-doll","preferenceTerms":["cute stuff","fabric","soft stuff"]},
  {"slug":"elegant-flower","preferenceTerms":["pretty flowers"]},
  {"slug":"excavation-tools","preferenceTerms":["metal stuff","strange stuff"]},
  {"slug":"extravagant-flowers","preferenceTerms":["containers","pretty flowers","stone stuff","watching stuff","wobbly stuff"]},
  {"slug":"fairy-feather","preferenceTerms":["cute stuff"]},
  {"slug":"fan","preferenceTerms":["electronics","metal stuff","nice breezes","spinning stuff"]},
  {"slug":"fancy-chair","preferenceTerms":["fabric","luxury","soft stuff","spinning stuff"]},
  {"slug":"fancy-pen","preferenceTerms":["luxury","metal stuff","slender objects"]},
  {"slug":"fiery-magby-statue","preferenceTerms":["lots of fire","stone stuff","strange stuff"]},
  {"slug":"fire-hydrant","preferenceTerms":["lots of water","metal stuff","shiny stuff"]},
  {"slug":"firepit","preferenceTerms":["group activities","lots of fire","round stuff","stone stuff"]},
  {"slug":"firework-blue","preferenceTerms":["round stuff"]},
  {"slug":"firework-green","preferenceTerms":["round stuff"]},
  {"slug":"firework-red","preferenceTerms":["round stuff"]},
  {"slug":"firework-white","preferenceTerms":["round stuff"]},
  {"slug":"firework-yellow","preferenceTerms":["round stuff"]},
  {"slug":"first-aid-kit","preferenceTerms":["colorful stuff","containers","healing","metal stuff"]},
  {"slug":"fishing-rod","preferenceTerms":["metal stuff","ocean vibes","slender objects","wobbly stuff"]},
  {"slug":"flame-orb","preferenceTerms":["round stuff"]},
  {"slug":"flat-leaf-plant","preferenceTerms":["containers","lots of nature","pretty flowers","slender objects","watching stuff"]},
  {"slug":"floor-switch","preferenceTerms":["electronics"]},
  {"slug":"fluff","preferenceTerms":["fabric","round stuff","soft stuff"]},
  {"slug":"fluorescent-light","preferenceTerms":["electronics","glass stuff","shiny stuff","slender objects"]},
  {"slug":"folding-chair","preferenceTerms":["metal stuff","wobbly stuff"]},
  {"slug":"food-counter","preferenceTerms":["wooden stuff"]},
  {"slug":"fortree-city","preferenceTerms":["round stuff"]},
  {"slug":"frame","preferenceTerms":["blocky stuff","containers","letters and words","watching stuff","wooden stuff"]},
  {"slug":"fried-potatoes","preferenceTerms":["colorful stuff","gatherings","looks like food"]},
  {"slug":"fuchsia-city-theme","preferenceTerms":["round stuff"]},
  {"slug":"funky-diffuser","preferenceTerms":["lots of water","metal stuff","strange stuff"]},
  {"slug":"game-boy-system","preferenceTerms":["blocky stuff","electronics","group activities"]},
  {"slug":"game-corner","preferenceTerms":["round stuff"]},
  {"slug":"gaming-bed","preferenceTerms":["colorful stuff","electronics","group activities","shiny stuff","soft stuff"]},
  {"slug":"gaming-chair","preferenceTerms":["colorful stuff","electronics","fabric","luxury","shiny stuff","soft stuff","spinning stuff"]},
  {"slug":"gaming-fridge","preferenceTerms":["colorful stuff","containers","electronics","glass stuff","metal stuff"]},
  {"slug":"gaming-light","preferenceTerms":["colorful stuff","electronics","gatherings","glass stuff"]},
  {"slug":"gaming-pc","preferenceTerms":["colorful stuff","electronics","glass stuff","metal stuff","shiny stuff"]},
  {"slug":"garbage-bags","preferenceTerms":["garbage","gatherings"]},
  {"slug":"garbage-bin","preferenceTerms":["containers","garbage","metal stuff"]},
  {"slug":"garden-bench","preferenceTerms":["group activities","lots of nature","metal stuff"]},
  {"slug":"garden-chair","preferenceTerms":["lots of nature","metal stuff"]},
  {"slug":"garden-flowers","preferenceTerms":["colorful stuff","pretty flowers"]},
  {"slug":"garden-light","preferenceTerms":["electronics","glass stuff","metal stuff"]},
  {"slug":"garden-ornament","preferenceTerms":["gatherings","stone stuff"]},
  {"slug":"garden-table","preferenceTerms":["lots of nature"]},
  {"slug":"glass","preferenceTerms":["glass stuff"]},
  {"slug":"glass-window","preferenceTerms":["glass stuff"]},
  {"slug":"gold-bottle-cap","preferenceTerms":["round stuff","shiny stuff"]},
  {"slug":"gold-ingot","preferenceTerms":["metal stuff"]},
  {"slug":"gold-ore","preferenceTerms":["metal stuff"]},
  {"slug":"gold-teeth","preferenceTerms":["metal stuff","shiny stuff","stone stuff","strange stuff"]},
  {"slug":"gravestone","preferenceTerms":["letters and words","spooky stuff","strange stuff"]},
  {"slug":"green-meteor-lamp","preferenceTerms":["cute stuff","electronics","glass stuff","shiny stuff"]},
  {"slug":"green-paint","preferenceTerms":["colorful stuff","lots of dirt"]},
  {"slug":"grubby-book","preferenceTerms":["complicated stuff","garbage","letters and words"]},
  {"slug":"grubby-cell-phone","preferenceTerms":["garbage"]},
  {"slug":"grubby-letter","preferenceTerms":["complicated stuff","garbage","letters and words"]},
  {"slug":"grubby-newspaper","preferenceTerms":["complicated stuff","garbage","letters and words","watching stuff"]},
  {"slug":"grubby-notepad","preferenceTerms":["complicated stuff","garbage","letters and words"]},
  {"slug":"grubby-papers","preferenceTerms":["complicated stuff","garbage","letters and words"]},
  {"slug":"grubby-tablet","preferenceTerms":["garbage"]},
  {"slug":"guest-room-bed","preferenceTerms":["fabric","group activities","luxury","soft stuff","wooden stuff"]},
  {"slug":"gym-emblem-statue","preferenceTerms":["shiny stuff","stone stuff"]},
  {"slug":"handcar","preferenceTerms":["rides"]},
  {"slug":"hanging-banner","preferenceTerms":["colorful stuff","fabric"]},
  {"slug":"hanging-scroll","preferenceTerms":["blocky stuff","letters and words","strange stuff"]},
  {"slug":"harbor-streetlight","preferenceTerms":["electronics","glass stuff","metal stuff","ocean vibes","slender objects"]},
  {"slug":"hauoli-city-day","preferenceTerms":["round stuff"]},
  {"slug":"headbutt-fossil-body","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"headbutt-fossil-head","preferenceTerms":["hard stuff","lots of dirt","luxury","strange stuff"]},
  {"slug":"headbutt-fossil-tail","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"heart-scale","preferenceTerms":["cute stuff"]},
  {"slug":"horsea-fountain","preferenceTerms":["lots of water","ocean vibes","stone stuff","strange stuff"]},
  {"slug":"humidifier","preferenceTerms":["electronics","glass stuff","healing","lots of water","round stuff","strange stuff"]},
  {"slug":"indigo-meteor-lamp","preferenceTerms":["cute stuff","electronics","glass stuff","shiny stuff"]},
  {"slug":"industrial-bed","preferenceTerms":["fabric","group activities","metal stuff","soft stuff"]},
  {"slug":"industrial-bench","preferenceTerms":["group activities","metal stuff"]},
  {"slug":"industrial-chair","preferenceTerms":["metal stuff"]},
  {"slug":"industrial-desk","preferenceTerms":["metal stuff"]},
  {"slug":"inflatable-boat","preferenceTerms":["blocky stuff","group activities","lots of water","wobbly stuff"]},
  {"slug":"information-board","preferenceTerms":["letters and words","metal stuff","shiny stuff","stone stuff","symbols"]},
  {"slug":"iron-ball","preferenceTerms":["hard stuff","round stuff"]},
  {"slug":"iron-bed","preferenceTerms":["fabric","metal stuff","soft stuff"]},
  {"slug":"iron-bench","preferenceTerms":["group activities","metal stuff"]},
  {"slug":"iron-chair","preferenceTerms":["blocky stuff","metal stuff"]},
  {"slug":"iron-deposit","preferenceTerms":["metal stuff"]},
  {"slug":"iron-door","preferenceTerms":["metal stuff"]},
  {"slug":"iron-gate","preferenceTerms":["metal stuff"]},
  {"slug":"iron-ingot","preferenceTerms":["metal stuff"]},
  {"slug":"iron-ladder","preferenceTerms":["metal stuff"]},
  {"slug":"iron-ore","preferenceTerms":["metal stuff"]},
  {"slug":"iron-pipes","preferenceTerms":["construction","gatherings","metal stuff"]},
  {"slug":"iron-plate-flooring","preferenceTerms":["metal stuff"]},
  {"slug":"iron-plate-flooring-interior","preferenceTerms":["metal stuff"]},
  {"slug":"iron-rack","preferenceTerms":["hard stuff"]},
  {"slug":"iron-scaffold","preferenceTerms":["construction"]},
  {"slug":"iron-scaffold-plank","preferenceTerms":["construction"]},
  {"slug":"iron-stand","preferenceTerms":["blocky stuff","containers","hard stuff","metal stuff","shiny stuff"]},
  {"slug":"iron-steps","preferenceTerms":["metal stuff"]},
  {"slug":"iron-table","preferenceTerms":["hard stuff","metal stuff"]},
  {"slug":"iron-wall","preferenceTerms":["metal stuff"]},
  {"slug":"jaw-fossil","preferenceTerms":["hard stuff","lots of dirt","luxury","strange stuff"]},
  {"slug":"jubilife-village","preferenceTerms":["round stuff"]},
  {"slug":"jumbled-cords","preferenceTerms":["complicated stuff","containers","electronics","garbage","gatherings","group activities","metal stuff"]},
  {"slug":"knitting-supplies","preferenceTerms":["colorful stuff","fabric","gatherings","group activities","lots of dirt","round stuff","soft stuff"]},
  {"slug":"lagging-tail","preferenceTerms":["hard stuff"]},
  {"slug":"lantern","preferenceTerms":["electronics","glass stuff","metal stuff"]},
  {"slug":"laptop","preferenceTerms":["blocky stuff","electronics","glass stuff","metal stuff","shiny stuff"]},
  {"slug":"large-lost-relic","preferenceTerms":["strange stuff"]},
  {"slug":"large-mirror","preferenceTerms":["blocky stuff","glass stuff","luxury","strange stuff"]},
  {"slug":"large-ventilation-fan","preferenceTerms":["blocky stuff","metal stuff","nice breezes","spinning stuff","strange stuff"]},
  {"slug":"laser-sensor","preferenceTerms":["electronics"]},
  {"slug":"leafy-plant","preferenceTerms":["containers","pretty flowers","watching stuff","wobbly stuff"]},
  {"slug":"leftovers","preferenceTerms":["looks like food"]},
  {"slug":"letter","preferenceTerms":["blocky stuff","complicated stuff","letters and words","watching stuff"]},
  {"slug":"life-orb","preferenceTerms":["round stuff"]},
  {"slug":"light-clay","preferenceTerms":["soft stuff","stone stuff"]},
  {"slug":"log-bed","preferenceTerms":["blocky stuff","colorful stuff","fabric","lots of nature","soft stuff","wooden stuff"]},
  {"slug":"log-chair","preferenceTerms":["lots of nature","wooden stuff"]},
  {"slug":"log-table","preferenceTerms":["lots of nature","wooden stuff"]},
  {"slug":"lucky-egg","preferenceTerms":["round stuff"]},
  {"slug":"luxury-bed","preferenceTerms":["group activities","luxury","soft stuff","stone stuff"]},
  {"slug":"luxury-chair","preferenceTerms":["luxury","metal stuff","spooky stuff"]},
  {"slug":"luxury-dresser","preferenceTerms":["containers","glass stuff","luxury","strange stuff"]},
  {"slug":"luxury-lamp","preferenceTerms":["cute stuff","electronics","fabric","glass stuff","luxury","slender objects"]},
  {"slug":"luxury-sofa","preferenceTerms":["fabric","group activities","luxury","soft stuff"]},
  {"slug":"luxury-table","preferenceTerms":["luxury"]},
  {"slug":"magazine-rack","preferenceTerms":["colorful stuff","complicated stuff","containers","gatherings","watching stuff","wooden stuff"]},
  {"slug":"mailbox","preferenceTerms":["containers","metal stuff"]},
  {"slug":"malicious-armor","preferenceTerms":["luxury","strange stuff"]},
  {"slug":"menu-board","preferenceTerms":["blocky stuff","letters and words","wooden stuff"]},
  {"slug":"metal-chain","preferenceTerms":["metal stuff","slender objects"]},
  {"slug":"metal-drum","preferenceTerms":["construction","containers","metal stuff","round stuff"]},
  {"slug":"metal-powder","preferenceTerms":["shiny stuff"]},
  {"slug":"metallic-smelting-furnace","preferenceTerms":["lots of fire"]},
  {"slug":"microscope","preferenceTerms":["complicated stuff","glass stuff","metal stuff","strange stuff","watching stuff"]},
  {"slug":"microwave-oven","preferenceTerms":["blocky stuff","electronics","glass stuff","metal stuff","strange stuff"]},
  {"slug":"mini-bookcase","preferenceTerms":["blocky stuff","colorful stuff","containers","watching stuff","wooden stuff"]},
  {"slug":"mini-floodgate","preferenceTerms":["cute stuff"]},
  {"slug":"mini-generator","preferenceTerms":["blocky stuff","electronics","metal stuff","shiny stuff","strange stuff"]},
  {"slug":"mini-plain-bed","preferenceTerms":["blocky stuff","fabric","soft stuff"]},
  {"slug":"miracle-seed","preferenceTerms":["lots of nature"]},
  {"slug":"mirror-ball","preferenceTerms":["electronics","glass stuff","metal stuff","round stuff","shiny stuff"]},
  {"slug":"model-planet","preferenceTerms":["colorful stuff","cute stuff","electronics","metal stuff","round stuff","spinning stuff"]},
  {"slug":"model-space-shuttle","preferenceTerms":["metal stuff","nice breezes","rides","shiny stuff","stone stuff"]},
  {"slug":"modern-door","preferenceTerms":["glass stuff"]},
  {"slug":"modern-sink","preferenceTerms":["blocky stuff","cleanliness","lots of water","metal stuff","strange stuff"]},
  {"slug":"mountain-flowers","preferenceTerms":["pretty flowers"]},
  {"slug":"mt-coronet","preferenceTerms":["round stuff"]},
  {"slug":"mug","preferenceTerms":["containers","symbols"]},
  {"slug":"munna-bank","preferenceTerms":["containers","cute stuff","spooky stuff","stone stuff"]},
  {"slug":"mushroom-lamp","preferenceTerms":["electronics","slender objects","wooden stuff"]},
  {"slug":"mushroom-streetlight","preferenceTerms":["shiny stuff","slender objects","spooky stuff"]},
  {"slug":"music-mat-fa","preferenceTerms":["noisy stuff","play spaces","shiny stuff","strange stuff"]},
  {"slug":"music-mat-high-do","preferenceTerms":["noisy stuff","play spaces","shiny stuff","strange stuff"]},
  {"slug":"music-mat-la","preferenceTerms":["noisy stuff","play spaces","shiny stuff","strange stuff"]},
  {"slug":"music-mat-low-do","preferenceTerms":["noisy stuff","play spaces","shiny stuff","strange stuff"]},
  {"slug":"music-mat-mi","preferenceTerms":["noisy stuff","play spaces","shiny stuff","strange stuff"]},
  {"slug":"music-mat-re","preferenceTerms":["noisy stuff","play spaces","shiny stuff","strange stuff"]},
  {"slug":"music-mat-sol","preferenceTerms":["noisy stuff","play spaces","shiny stuff","strange stuff"]},
  {"slug":"music-mat-ti","preferenceTerms":["noisy stuff","play spaces","shiny stuff","strange stuff"]},
  {"slug":"mysterious-statue","preferenceTerms":["spooky stuff","stone stuff","strange stuff"]},
  {"slug":"mystic-water","preferenceTerms":["lots of water"]},
  {"slug":"naptime-bed","preferenceTerms":["soft stuff"]},
  {"slug":"newspaper","preferenceTerms":["blocky stuff","complicated stuff","letters and words","watching stuff"]},
  {"slug":"nonburnable-garbage","preferenceTerms":["garbage"]},
  {"slug":"nonburnable-garbage-outdoor","preferenceTerms":["garbage"]},
  {"slug":"notepad","preferenceTerms":["blocky stuff","complicated stuff","letters and words","watching stuff"]},
  {"slug":"nugget","preferenceTerms":["round stuff","shiny stuff"]},
  {"slug":"office-cabinet","preferenceTerms":["blocky stuff","containers","metal stuff","wooden stuff"]},
  {"slug":"office-chair","preferenceTerms":["fabric","metal stuff","soft stuff","spinning stuff"]},
  {"slug":"office-desk","preferenceTerms":["metal stuff"]},
  {"slug":"office-locker","preferenceTerms":["blocky stuff","containers","metal stuff"]},
  {"slug":"office-shelf","preferenceTerms":["blocky stuff","containers","gatherings","glass stuff","letters and words","metal stuff"]},
  {"slug":"open-book","preferenceTerms":["blocky stuff","complicated stuff","letters and words","watching stuff"]},
  {"slug":"orange-meteor-lamp","preferenceTerms":["cute stuff","electronics","glass stuff","shiny stuff"]},
  {"slug":"paint-balloon-aquamarine","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-beige","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-black","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-blue","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-brown","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-cyan","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-gray","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-green","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-lime","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-navy","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-orange","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-pink","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-plum","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-purple","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-red","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-rose","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-white","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"paint-balloon-yellow","preferenceTerms":["colorful stuff","round stuff"]},
  {"slug":"painting-landscape","preferenceTerms":["colorful stuff","fabric","watching stuff"]},
  {"slug":"painting-portrait","preferenceTerms":["colorful stuff","fabric","watching stuff"]},
  {"slug":"painting-still-life","preferenceTerms":["colorful stuff","fabric","watching stuff"]},
  {"slug":"pallet-town-theme","preferenceTerms":["round stuff"]},
  {"slug":"paper-party-cups","preferenceTerms":["gatherings","group activities","lots of water"]},
  {"slug":"papers","preferenceTerms":["blocky stuff","complicated stuff","letters and words","watching stuff"]},
  {"slug":"party-bunting","preferenceTerms":["colorful stuff","fabric"]},
  {"slug":"pencil-holder","preferenceTerms":["complicated stuff","containers","gatherings","stone stuff"]},
  {"slug":"pewter-city-theme","preferenceTerms":["round stuff"]},
  {"slug":"photo-cutout-board","preferenceTerms":["colorful stuff","cute stuff","gatherings","group activities","watching stuff"]},
  {"slug":"photo-frame","preferenceTerms":["blocky stuff","containers","group activities","watching stuff"]},
  {"slug":"picnic-basket","preferenceTerms":["blocky stuff","containers","fabric","group activities"]},
  {"slug":"pikachu-doll","preferenceTerms":["cute stuff","fabric","soft stuff"]},
  {"slug":"pikachu-sofa","preferenceTerms":["colorful stuff","cute stuff","fabric","group activities","soft stuff"]},
  {"slug":"pink-paint","preferenceTerms":["colorful stuff","lots of dirt"]},
  {"slug":"pinwheels","preferenceTerms":["colorful stuff","gatherings","nice breezes","play spaces","spinning stuff","watching stuff"]},
  {"slug":"pitcher-plant-pot","preferenceTerms":["containers","spooky stuff","stone stuff","watching stuff","wobbly stuff"]},
  {"slug":"pizza","preferenceTerms":["colorful stuff","looks like food","round stuff"]},
  {"slug":"plain-bed","preferenceTerms":["fabric","group activities","soft stuff"]},
  {"slug":"plain-chair","preferenceTerms":["fabric","soft stuff","wooden stuff"]},
  {"slug":"plain-chest","preferenceTerms":["blocky stuff","containers","fabric","wooden stuff"]},
  {"slug":"plain-closet","preferenceTerms":["blocky stuff","containers","fabric","wooden stuff"]},
  {"slug":"plain-lamp","preferenceTerms":["electronics","fabric","glass stuff","wooden stuff"]},
  {"slug":"plain-sofa","preferenceTerms":["fabric","group activities","soft stuff"]},
  {"slug":"plain-stand","preferenceTerms":["blocky stuff","containers","fabric","wooden stuff"]},
  {"slug":"plain-stool","preferenceTerms":["fabric","soft stuff"]},
  {"slug":"plain-table","preferenceTerms":["wooden stuff"]},
  {"slug":"poke-ball-bed","preferenceTerms":["fabric","soft stuff"]},
  {"slug":"poke-ball-chest","preferenceTerms":["containers","cute stuff","metal stuff","round stuff","shiny stuff"]},
  {"slug":"poke-ball-lamp","preferenceTerms":["electronics","glass stuff","luxury","round stuff","strange stuff"]},
  {"slug":"poke-ball-light","preferenceTerms":["colorful stuff","electronics","glass stuff","luxury","metal stuff"]},
  {"slug":"poke-ball-sofa","preferenceTerms":["group activities","metal stuff"]},
  {"slug":"pokemetal","preferenceTerms":["colorful stuff","metal stuff"]},
  {"slug":"pokemetal-fragment","preferenceTerms":["metal stuff"]},
  {"slug":"pokemon-center","preferenceTerms":["round stuff"]},
  {"slug":"pokemon-gym","preferenceTerms":["round stuff"]},
  {"slug":"polygonal-shelf","preferenceTerms":["containers","cute stuff","strange stuff"]},
  {"slug":"pop-art-bed","preferenceTerms":["cute stuff","fabric","group activities","soft stuff"]},
  {"slug":"pop-art-chair","preferenceTerms":["colorful stuff","cute stuff","fabric","soft stuff"]},
  {"slug":"pop-art-lamp","preferenceTerms":["electronics","glass stuff"]},
  {"slug":"pop-art-sofa","preferenceTerms":["colorful stuff","cute stuff","fabric","group activities","soft stuff"]},
  {"slug":"pop-art-table","preferenceTerms":["cute stuff"]},
  {"slug":"printer","preferenceTerms":["electronics","glass stuff","strange stuff"]},
  {"slug":"professor-oaks-laboratory","preferenceTerms":["round stuff"]},
  {"slug":"public-seat","preferenceTerms":["blocky stuff","metal stuff"]},
  {"slug":"punching-bag","preferenceTerms":["exercise","fabric","lots of dirt","wobbly stuff"]},
  {"slug":"punching-game","preferenceTerms":["colorful stuff","exercise","play spaces","wobbly stuff"]},
  {"slug":"raichu-sign","preferenceTerms":["colorful stuff","glass stuff","letters and words"]},
  {"slug":"rainbow-feather","preferenceTerms":["shiny stuff"]},
  {"slug":"rare-pokemetal-fragment","preferenceTerms":["metal stuff"]},
  {"slug":"recycling-bin","preferenceTerms":["containers","garbage","metal stuff"]},
  {"slug":"red-meteor-lamp","preferenceTerms":["cute stuff","electronics","glass stuff","shiny stuff"]},
  {"slug":"red-paint","preferenceTerms":["colorful stuff","lots of dirt"]},
  {"slug":"refrigerator","preferenceTerms":["blocky stuff","containers","electronics","metal stuff","strange stuff"]},
  {"slug":"repel","preferenceTerms":["strange stuff"]},
  {"slug":"resort-bed","preferenceTerms":["fabric","ocean vibes","soft stuff"]},
  {"slug":"resort-chair","preferenceTerms":["fabric","ocean vibes","soft stuff"]},
  {"slug":"resort-hammock","preferenceTerms":["fabric","lots of water","ocean vibes","soft stuff","wobbly stuff"]},
  {"slug":"resort-light","preferenceTerms":["electronics","metal stuff","ocean vibes","wobbly stuff"]},
  {"slug":"resort-sofa","preferenceTerms":["fabric","group activities","ocean vibes","soft stuff"]},
  {"slug":"resort-stool","preferenceTerms":["fabric","ocean vibes","soft stuff"]},
  {"slug":"ribbon-cake","preferenceTerms":["colorful stuff","cute stuff","looks like food","round stuff"]},
  {"slug":"ring-target","preferenceTerms":["round stuff"]},
  {"slug":"road-to-bill","preferenceTerms":["round stuff"]},
  {"slug":"road-to-cerulean-city","preferenceTerms":["round stuff"]},
  {"slug":"road-to-viridian-city","preferenceTerms":["round stuff"]},
  {"slug":"robust-flower","preferenceTerms":["pretty flowers"]},
  {"slug":"rocket-hideout","preferenceTerms":["round stuff"]},
  {"slug":"room-service","preferenceTerms":["fabric"]},
  {"slug":"rope","preferenceTerms":["slender objects"]},
  {"slug":"rose-tower","preferenceTerms":["round stuff"]},
  {"slug":"route-10-unova","preferenceTerms":["round stuff"]},
  {"slug":"route-209-day","preferenceTerms":["round stuff"]},
  {"slug":"rowlet-clock","preferenceTerms":["cute stuff","strange stuff","watching stuff"]},
  {"slug":"sail-fossil","preferenceTerms":["hard stuff","lots of dirt","luxury","strange stuff"]},
  {"slug":"sandbags","preferenceTerms":["construction","fabric","gatherings","lots of dirt"]},
  {"slug":"sandbox","preferenceTerms":["blocky stuff","group activities","lots of dirt","play spaces"]},
  {"slug":"sandwiches","preferenceTerms":["blocky stuff","colorful stuff","gatherings","looks like food"]},
  {"slug":"sash-window","preferenceTerms":["glass stuff"]},
  {"slug":"science-experiment","preferenceTerms":["complicated stuff","gatherings","glass stuff","letters and words","metal stuff"]},
  {"slug":"sea-glass-fragments","preferenceTerms":["glass stuff"]},
  {"slug":"seashore-flowers","preferenceTerms":["pretty flowers"]},
  {"slug":"security-camera","preferenceTerms":["electronics"]},
  {"slug":"seedot-lamp","preferenceTerms":["electronics","glass stuff","lots of nature","round stuff"]},
  {"slug":"shaved-ice","preferenceTerms":["colorful stuff","looks like food","lots of water"]},
  {"slug":"shell-lamp","preferenceTerms":["cute stuff","electronics","glass stuff","ocean vibes"]},
  {"slug":"shield-fossil-body","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"shield-fossil-head","preferenceTerms":["hard stuff","lots of dirt","luxury","strange stuff"]},
  {"slug":"shield-fossil-tail","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"ships-wheel","preferenceTerms":["ocean vibes","round stuff"]},
  {"slug":"shower","preferenceTerms":["cleanliness","lots of water","metal stuff","slender objects","strange stuff"]},
  {"slug":"sign","preferenceTerms":["letters and words","symbols","wooden stuff"]},
  {"slug":"signpost","preferenceTerms":["letters and words","metal stuff","shiny stuff","stone stuff","symbols"]},
  {"slug":"silk-scarf","preferenceTerms":["fabric"]},
  {"slug":"silph-co","preferenceTerms":["round stuff"]},
  {"slug":"silver-bottle-cap","preferenceTerms":["round stuff","shiny stuff"]},
  {"slug":"silver-feather","preferenceTerms":["shiny stuff"]},
  {"slug":"silver-powder","preferenceTerms":["lots of nature"]},
  {"slug":"simple-cushion","preferenceTerms":["fabric","soft stuff"]},
  {"slug":"sink","preferenceTerms":["blocky stuff","cleanliness","lots of water","stone stuff","strange stuff"]},
  {"slug":"skull-fossil","preferenceTerms":["hard stuff","lots of dirt","luxury","strange stuff"]},
  {"slug":"skyland-flowers","preferenceTerms":["pretty flowers"]},
  {"slug":"slender-candle","preferenceTerms":["lots of fire","luxury","slender objects","spooky stuff","stone stuff"]},
  {"slug":"slide","preferenceTerms":["group activities","play spaces","wooden stuff"]},
  {"slug":"small-garbage-can","preferenceTerms":["containers","garbage","metal stuff","round stuff"]},
  {"slug":"small-lost-relic","preferenceTerms":["strange stuff"]},
  {"slug":"small-stage","preferenceTerms":["group activities","metal stuff","play spaces","round stuff","spinning stuff","strange stuff"]},
  {"slug":"small-vase","preferenceTerms":["containers","pretty flowers","slender objects","stone stuff","watching stuff"]},
  {"slug":"smelting-furnace","preferenceTerms":["lots of fire"]},
  {"slug":"snowbelle-city","preferenceTerms":["round stuff"]},
  {"slug":"soda-float","preferenceTerms":["colorful stuff","looks like food","lots of water"]},
  {"slug":"soft-sand","preferenceTerms":["soft stuff"]},
  {"slug":"soft-seat","preferenceTerms":["blocky stuff","fabric","soft stuff"]},
  {"slug":"sootopolis-city","preferenceTerms":["round stuff"]},
  {"slug":"south-province","preferenceTerms":["round stuff"]},
  {"slug":"spaceship","preferenceTerms":["glass stuff","metal stuff","rides","round stuff","stone stuff"]},
  {"slug":"spacesuit","preferenceTerms":["complicated stuff","glass stuff","metal stuff","shiny stuff","stone stuff"]},
  {"slug":"speaker","preferenceTerms":["blocky stuff","electronics","noisy stuff"]},
  {"slug":"spectator-chair","preferenceTerms":["metal stuff"]},
  {"slug":"spell-tag","preferenceTerms":["spooky stuff"]},
  {"slug":"spotlight","preferenceTerms":["electronics","glass stuff","metal stuff"]},
  {"slug":"sprinkler","preferenceTerms":["lots of water","metal stuff","stone stuff","strange stuff"]},
  {"slug":"squishy-clay","preferenceTerms":["soft stuff"]},
  {"slug":"stained-glass-window-lower","preferenceTerms":["glass stuff"]},
  {"slug":"stained-glass-window-middle","preferenceTerms":["glass stuff"]},
  {"slug":"stained-glass-window-upper","preferenceTerms":["glass stuff"]},
  {"slug":"standing-mic","preferenceTerms":["electronics","group activities","hard stuff","shiny stuff","strange stuff"]},
  {"slug":"star-piece","preferenceTerms":["shiny stuff"]},
  {"slug":"stardust","preferenceTerms":["shiny stuff"]},
  {"slug":"step-stool","preferenceTerms":["metal stuff","rides"]},
  {"slug":"stone","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-bench","preferenceTerms":["group activities","hard stuff","stone stuff"]},
  {"slug":"stone-brick-wall","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-brick-wall-interior","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-fireplace","preferenceTerms":["blocky stuff","colorful stuff","hard stuff","luxury","stone stuff"]},
  {"slug":"stone-flooring","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-flooring-interior","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-hipped-roof","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-pillar-lower","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-pillar-middle","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-pillar-upper","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-roof-decoration","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-roof-valley","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-steps","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-table","preferenceTerms":["hard stuff"]},
  {"slug":"stone-tiling","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"stone-tiling-interior","preferenceTerms":["hard stuff","stone stuff"]},
  {"slug":"storage-box","preferenceTerms":["wooden stuff"]},
  {"slug":"straw-bed","preferenceTerms":["lots of nature","soft stuff"]},
  {"slug":"straw-stool","preferenceTerms":["soft stuff"]},
  {"slug":"straw-table","preferenceTerms":["lots of nature"]},
  {"slug":"strength-rock","preferenceTerms":["hard stuff"]},
  {"slug":"string-lights","preferenceTerms":["electronics","gatherings","glass stuff"]},
  {"slug":"study-desk","preferenceTerms":["wooden stuff"]},
  {"slug":"stylish-stool","preferenceTerms":["colorful stuff","cute stuff","fabric","soft stuff"]},
  {"slug":"substitute-doll","preferenceTerms":["cute stuff","fabric","soft stuff"]},
  {"slug":"super-training","preferenceTerms":["round stuff"]},
  {"slug":"surface-light","preferenceTerms":["electronics","glass stuff","round stuff"]},
  {"slug":"table-setting","preferenceTerms":["fabric","gatherings","group activities","looks like food"]},
  {"slug":"tablet","preferenceTerms":["blocky stuff","electronics","glass stuff","metal stuff","shiny stuff"]},
  {"slug":"tabletop-mic","preferenceTerms":["electronics","shiny stuff"]},
  {"slug":"tall-potted-plant","preferenceTerms":["containers","lots of nature","pretty flowers","slender objects","stone stuff","watching stuff"]},
  {"slug":"tea-set","preferenceTerms":["containers","gatherings","group activities"]},
  {"slug":"team-rocket-wall-hanging","preferenceTerms":["blocky stuff","metal stuff","symbols","watching stuff"]},
  {"slug":"television","preferenceTerms":["blocky stuff","electronics","glass stuff","group activities","letters and words","metal stuff","shiny stuff","watching stuff"]},
  {"slug":"the-academy","preferenceTerms":["round stuff"]},
  {"slug":"the-s-s-anne","preferenceTerms":["round stuff"]},
  {"slug":"tidal-bell","preferenceTerms":["nice breezes","noisy stuff","round stuff","strange stuff"]},
  {"slug":"tire-toy","preferenceTerms":["group activities","play spaces","round stuff","wobbly stuff"]},
  {"slug":"tires","preferenceTerms":["gatherings","round stuff","wobbly stuff"]},
  {"slug":"title-screen","preferenceTerms":["round stuff"]},
  {"slug":"toilet","preferenceTerms":["cleanliness","electronics","lots of water","stone stuff","strange stuff"]},
  {"slug":"torch","preferenceTerms":["lots of fire"]},
  {"slug":"towel-rack","preferenceTerms":["cleanliness","fabric","soft stuff"]},
  {"slug":"town-map","preferenceTerms":["blocky stuff","complicated stuff","strange stuff","watching stuff"]},
  {"slug":"town-streetlight","preferenceTerms":["electronics","glass stuff","metal stuff","slender objects"]},
  {"slug":"toy-blocks","preferenceTerms":["construction","gatherings","play spaces","wooden stuff"]},
  {"slug":"tundra-fossil-body","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"tundra-fossil-head","preferenceTerms":["hard stuff","lots of dirt","luxury","strange stuff"]},
  {"slug":"tundra-fossil-tail","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"twine","preferenceTerms":["slender objects"]},
  {"slug":"twisted-potted-plant","preferenceTerms":["containers","lots of nature","pretty flowers","slender objects","watching stuff"]},
  {"slug":"twisted-spoon","preferenceTerms":["strange stuff"]},
  {"slug":"ultra-ruin","preferenceTerms":["round stuff"]},
  {"slug":"union-cave","preferenceTerms":["round stuff"]},
  {"slug":"utility-pole","preferenceTerms":["electronics"]},
  {"slug":"vending-machine","preferenceTerms":["blocky stuff","glass stuff","group activities","metal stuff","sharp stuff"]},
  {"slug":"vermilion-city-theme","preferenceTerms":["round stuff"]},
  {"slug":"vine-rope","preferenceTerms":["slender objects"]},
  {"slug":"vine-wall-decoration","preferenceTerms":["lots of nature","slender objects","wooden stuff"]},
  {"slug":"violet-meteor-lamp","preferenceTerms":["cute stuff","electronics","glass stuff","shiny stuff"]},
  {"slug":"wall-calendar","preferenceTerms":["blocky stuff","letters and words","watching stuff"]},
  {"slug":"wall-light","preferenceTerms":["blocky stuff","electronics","glass stuff"]},
  {"slug":"wall-mirror","preferenceTerms":["blocky stuff","glass stuff","luxury","strange stuff","watching stuff"]},
  {"slug":"wall-monitor","preferenceTerms":["blocky stuff","electronics","glass stuff","group activities","letters and words","metal stuff","shiny stuff","watching stuff"]},
  {"slug":"wall-mounted-flowers","preferenceTerms":["colorful stuff","pretty flowers"]},
  {"slug":"wall-photo-frame","preferenceTerms":["blocky stuff","containers","watching stuff"]},
  {"slug":"wall-storage-box","preferenceTerms":["blocky stuff","containers","wooden stuff"]},
  {"slug":"wall-switch","preferenceTerms":["electronics"]},
  {"slug":"wall-torch","preferenceTerms":["lots of fire","stone stuff"]},
  {"slug":"washing-machine","preferenceTerms":["blocky stuff","cleanliness","containers","electronics","glass stuff","metal stuff","strange stuff"]},
  {"slug":"wastepaper","preferenceTerms":["garbage"]},
  {"slug":"water-basin","preferenceTerms":["cleanliness","colorful stuff","lots of water","round stuff","wooden stuff"]},
  {"slug":"water-pillar-quarter","preferenceTerms":["glass stuff","lots of water","watching stuff"]},
  {"slug":"waterproof-seat","preferenceTerms":["cleanliness"]},
  {"slug":"weakness-policy","preferenceTerms":["letters and words"]},
  {"slug":"weather-vane","preferenceTerms":["metal stuff","nice breezes","spinning stuff"]},
  {"slug":"wheelbarrow","preferenceTerms":["construction","containers","lots of dirt","metal stuff"]},
  {"slug":"white-paint","preferenceTerms":["colorful stuff","lots of dirt"]},
  {"slug":"whiteboard","preferenceTerms":["blocky stuff","gatherings","group activities","letters and words","shiny stuff"]},
  {"slug":"wiggly-mirror","preferenceTerms":["cute stuff","glass stuff","strange stuff","watching stuff"]},
  {"slug":"wild-area-north","preferenceTerms":["round stuff"]},
  {"slug":"wildflowers","preferenceTerms":["pretty flowers"]},
  {"slug":"window-pane","preferenceTerms":["glass stuff"]},
  {"slug":"wing-fossil-body","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"wing-fossil-head","preferenceTerms":["hard stuff","lots of dirt","luxury","strange stuff"]},
  {"slug":"wing-fossil-left-wing","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"wing-fossil-right-wing","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"wing-fossil-tail","preferenceTerms":["hard stuff","lots of dirt","luxury","slender objects","strange stuff"]},
  {"slug":"wire","preferenceTerms":["slender objects"]},
  {"slug":"wireless-power-transmitter","preferenceTerms":["electronics"]},
  {"slug":"wireless-power-transmitter-switch","preferenceTerms":["electronics"]},
  {"slug":"wobbuffet-wobbler","preferenceTerms":["cute stuff","exercise","play spaces","round stuff","strange stuff","wobbly stuff"]},
  {"slug":"wooden-bed","preferenceTerms":["group activities","lots of nature","soft stuff"]},
  {"slug":"wooden-bench","preferenceTerms":["group activities"]},
  {"slug":"wooden-birdhouse","preferenceTerms":["containers","slender objects","wooden stuff"]},
  {"slug":"wooden-crate","preferenceTerms":["blocky stuff","containers","wooden stuff"]},
  {"slug":"wooden-plate","preferenceTerms":["wooden stuff"]},
  {"slug":"wooden-stool","preferenceTerms":["blocky stuff"]},
  {"slug":"worn-wooden-crate","preferenceTerms":["blocky stuff","containers","wooden stuff"]},
  {"slug":"wreath","preferenceTerms":["round stuff","wooden stuff"]},
  {"slug":"wyndon","preferenceTerms":["round stuff"]},
  {"slug":"yellow-meteor-lamp","preferenceTerms":["cute stuff","electronics","glass stuff","shiny stuff"]},
  {"slug":"yellow-paint","preferenceTerms":["colorful stuff","lots of dirt"]},
] as const;
