export interface AssetFootprint {
  readonly length: number;
  readonly width: number;
  readonly height: number;
}

export const defaultAssetFootprint: AssetFootprint = {
  length: 1,
  width: 1,
  height: 1,
};

const assetFootprintOverridesByAssetId: Readonly<Record<string, AssetFootprint>> = {
  'stalagmites': { length: 1, width: 2, height: 2 },
  'pointy-tree': { length: 1, width: 1, height: 3 },
  'large-palm-tree': { length: 1, width: 1, height: 3 },
  'large-boulder': { length: 2, width: 2, height: 1 },
  'mossy-boulder': { length: 2, width: 2, height: 1 },
  'molten-rock': { length: 2, width: 2, height: 1 },
  'leppa-tree': { length: 1, width: 1, height: 3 },
  'driftwood': { length: 1, width: 2, height: 1 },
  'cooled-molten-rock': { length: 2, width: 2, height: 1 },
  'stalactites': { length: 1, width: 2, height: 2 },
  'icicle': { length: 1, width: 2, height: 2 },
  'crystal-cluster': { length: 2, width: 2, height: 1 },
  'strength-rock': { length: 1, width: 1, height: 2 },
  'plain-closet': { length: 1, width: 1, height: 2 },
  'wooden-bench': { length: 1, width: 2, height: 1 },
  'plain-stand': { length: 1, width: 2, height: 1 },
  'straw-bed': { length: 2, width: 2, height: 1 },
  'deck-chair': { length: 2, width: 1, height: 1 },
  'beach-chair': { length: 2, width: 1, height: 1 },
  'plain-sofa': { length: 1, width: 2, height: 1 },
  'garden-bench': { length: 1, width: 2, height: 1 },
  'small-narrow-rug': { length: 1, width: 2, height: 1 },
  'oblong-rug': { length: 1, width: 2, height: 1 },
  'large-round-rug': { length: 2, width: 2, height: 1 },
  'ratan-rug': { length: 3, width: 2, height: 1 },
  'lace-rug': { length: 3, width: 3, height: 1 },
  'large-narrow-rug': { length: 1, width: 2, height: 1 },
  'large-square-rug': { length: 4, width: 4, height: 1 },
  'log-bed': { length: 2, width: 1, height: 1 },
  'wooden-bed': { length: 2, width: 2, height: 1 },
  'big-storage-box': { length: 1, width: 2, height: 1 },
  'stone-bench': { length: 1, width: 2, height: 1 },
  'industrial-bed': { length: 2, width: 2, height: 1 },
  'antique-closet': { length: 1, width: 2, height: 1 },
  'antique-bed': { length: 2, width: 2, height: 1 },
  'chic-sofa': { length: 1, width: 2, height: 1 },
  'plain-table': { length: 1, width: 2, height: 1 },
  'resort-sofa': { length: 1, width: 2, height: 1 },
  'resort-table': { length: 2, width: 2, height: 1 },
  'resort-hammock': { length: 2, width: 2, height: 1 },
  'pop-art-bed': { length: 2, width: 2, height: 1 },
  'pop-art-sofa': { length: 1, width: 2, height: 1 },
  'pop-art-table': { length: 2, width: 2, height: 1 },
  'iron-table': { length: 1, width: 2, height: 1 },
  'mini-plain-bed': { length: 2, width: 1, height: 1 },
  'iron-bed': { length: 2, width: 1, height: 1 },
  'avalugg-table': { length: 2, width: 2, height: 1 },
  'pikachu-sofa': { length: 1, width: 2, height: 1 },
  'naptime-bed': { length: 2, width: 2, height: 1 },
  'iron-rack': { length: 1, width: 2, height: 1 },
  'food-counter': { length: 1, width: 2, height: 1 },
  'industrial-desk': { length: 1, width: 2, height: 1 },
  'iron-bench': { length: 1, width: 2, height: 1 },
  'iron-stand': { length: 1, width: 2, height: 1 },
  'office-desk': { length: 1, width: 2, height: 1 },
  'office-locker': { length: 1, width: 1, height: 2 },
  'office-table': { length: 2, width: 2, height: 1 },
  'plain-bed': { length: 2, width: 2, height: 1 },
  'stone-table': { length: 2, width: 2, height: 1 },
  'luxury-bed': { length: 2, width: 2, height: 1 },
  'luxury-sofa': { length: 1, width: 2, height: 1 },
  'luxury-table': { length: 2, width: 2, height: 1 },
  'counter': { length: 1, width: 1, height: 1 },
  'cute-sofa': { length: 1, width: 2, height: 1 },
  'cute-table': { length: 1, width: 2, height: 1 },
  'cute-bed': { length: 2, width: 2, height: 1 },
  'cute-dresser': { length: 1, width: 2, height: 1 },
  'gaming-bed': { length: 2, width: 2, height: 1 },
  'poke-ball-bed': { length: 2, width: 2, height: 1 },
  'poke-ball-table': { length: 2, width: 2, height: 1 },
  'office-shelf': { length: 1, width: 2, height: 1 },
  'chic-table': { length: 2, width: 2, height: 1 },
  'push-cart': { length: 1, width: 2, height: 1 },
  'berry-bed': { length: 2, width: 2, height: 1 },
  'berry-table': { length: 2, width: 2, height: 1 },
  'wall-storage-box': { length: 1, width: 2, height: 1 },
  'antique-chest': { length: 1, width: 2, height: 1 },
  'pokemon-center-counter': { length: 1, width: 2, height: 1 },
  'antique-table': { length: 1, width: 2, height: 1 },
  'study-desk': { length: 1, width: 2, height: 1 },
  'antique-sofa': { length: 1, width: 2, height: 1 },
  'industrial-bench': { length: 1, width: 2, height: 1 },
  'resort-bed': { length: 2, width: 1, height: 1 },
  'guest-room-bed': { length: 2, width: 2, height: 1 },
  'sleeping-bag': { length: 2, width: 1, height: 1 },
  'twisted-potted-plant': { length: 1, width: 1, height: 2 },
  'tall-potted-plant': { length: 1, width: 1, height: 2 },
  'extravagant-flowers': { length: 1, width: 1, height: 2 },
  'berry-basket': { length: 1, width: 2, height: 1 },
  'standing-mic': { length: 1, width: 1, height: 2 },
  'bookcase': { length: 1, width: 2, height: 2 },
  'arcanine-doll': { length: 1, width: 2, height: 1 },
  'dragonite-doll': { length: 1, width: 1, height: 2 },
  'bouncy-blue-bathtub': { length: 2, width: 1, height: 1 },
  'arcade-machine': { length: 1, width: 1, height: 2 },
  'boo-in-the-box': { length: 1, width: 1, height: 2 },
  'cool-electric-guitar': { length: 1, width: 1, height: 2 },
  'cool-bass-guitar': { length: 1, width: 1, height: 2 },
  'shower': { length: 1, width: 1, height: 2 },
  'speaker': { length: 1, width: 1, height: 2 },
  'punching-game': { length: 1, width: 1, height: 2 },
  'auspicious-armor': { length: 1, width: 1, height: 2 },
  'hanging-scroll': { length: 1, width: 1, height: 2 },
  'control-unit': { length: 2, width: 2, height: 1 },
  'jumbled-cords': { length: 1, width: 2, height: 1 },
  'stone-fireplace': { length: 1, width: 2, height: 2 },
  'gaming-pc': { length: 1, width: 2, height: 1 },
  'television': { length: 1, width: 2, height: 1 },
  'malicious-armor': { length: 1, width: 1, height: 2 },
  'whiteboard': { length: 1, width: 2, height: 1 },
  'computer': { length: 1, width: 2, height: 1 },
  'bathtub': { length: 2, width: 1, height: 1 },
  'refrigerator': { length: 1, width: 1, height: 2 },
  'air-conditioner': { length: 1, width: 2, height: 1 },
  'punching-bag': { length: 1, width: 1, height: 2 },
  'chansey-plant': { length: 2, width: 2, height: 3 },
  'beach-parasol': { length: 1, width: 1, height: 2 },
  'firepit': { length: 2, width: 2, height: 1 },
  'bonfire': { length: 1, width: 1, height: 2 },
  'horsea-fountain': { length: 1, width: 1, height: 2 },
  'gravestone': { length: 1, width: 1, height: 2 },
  'fishing-rod': { length: 1, width: 1, height: 2 },
  'iron-pipes': { length: 1, width: 2, height: 1 },
  'cart': { length: 1, width: 3, height: 1 },
  'wheelbarrow': { length: 1, width: 3, height: 1 },
  'canoe': { length: 2, width: 1, height: 1 },
  'inflatable-boat': { length: 2, width: 2, height: 1 },
  'information-board': { length: 1, width: 2, height: 1 },
  'raichu-sign': { length: 1, width: 2, height: 1 },
  'vending-machine': { length: 2, width: 1, height: 2 },
  'wooden-birdhouse': { length: 1, width: 1, height: 2 },
  'signpost': { length: 1, width: 1, height: 2 },
  'bike': { length: 1, width: 2, height: 1 },
  'photo-cutout-board': { length: 1, width: 2, height: 1 },
  'slide': { length: 1, width: 3, height: 2 },
  'mailbox': { length: 1, width: 1, height: 2 },
  'weather-vane': { length: 1, width: 1, height: 2 },
  'large-ventilation-fan': { length: 2, width: 2, height: 1 },
  'grubby-rags': { length: 2, width: 2, height: 1 },
  'workbench': { length: 1, width: 2, height: 1 },
  'bread-oven': { length: 1, width: 1, height: 2 },
  'mushroom-streetlight': { length: 1, width: 1, height: 3 },
  'community-box': { length: 1, width: 2, height: 1 },
  'utility-pole': { length: 1, width: 1, height: 3 },
  'crossing-gate': { length: 1, width: 2, height: 1 },
  'lift-platform': { length: 2, width: 2, height: 2 },
  'smelting-furnace': { length: 2, width: 2, height: 2 },
  'metallic-smelting-furnace': { length: 2, width: 2, height: 2 },
  'elevator-platform': { length: 2, width: 2, height: 2 },
  'town-streetlight': { length: 1, width: 1, height: 3 },
  'chic-streetlight': { length: 1, width: 1, height: 3 },
  'double-streetlight': { length: 1, width: 1, height: 3 },
  'curved-eave': { length: 2, width: 1, height: 1 },
  'rustic-door': { length: 1, width: 1, height: 2 },
  'iron-door': { length: 1, width: 2, height: 1 },
  'large-wooden-door': { length: 1, width: 2, height: 2 },
  'wooden-gate': { length: 1, width: 2, height: 1 },
  'iron-gate': { length: 1, width: 2, height: 1 },
  'automatic-doors': { length: 1, width: 2, height: 2 },
  'modern-door': { length: 1, width: 1, height: 2 },
  'sash-window': { length: 1, width: 1, height: 2 },
  'swinging-doors': { length: 1, width: 2, height: 1 },
  'grate-fencing': { length: 1, width: 2, height: 2 },
  'iron-scaffold': { length: 1, width: 2, height: 1 },
  'simple-door': { length: 1, width: 1, height: 2 },
  'boat-door': { length: 1, width: 1, height: 2 },
  'stylish-door': { length: 1, width: 1, height: 2 },
  'brainy-door': { length: 1, width: 1, height: 2 },
  'shutter': { length: 1, width: 2, height: 2 },
};

export const assetFootprintOverrideAssetIds: readonly string[] = Object.keys(assetFootprintOverridesByAssetId);

assertValidFootprints(assetFootprintOverridesByAssetId);

export function getAssetFootprint(assetId: string): AssetFootprint {
  return cloneAssetFootprint(assetFootprintOverridesByAssetId[assetId] ?? defaultAssetFootprint);
}

function cloneAssetFootprint(footprint: AssetFootprint): AssetFootprint {
  return {
    length: footprint.length,
    width: footprint.width,
    height: footprint.height,
  };
}

function assertValidFootprints(overrides: Readonly<Record<string, AssetFootprint>>): void {
  for (const [assetId, footprint] of Object.entries(overrides)) {
    for (const [fieldName, value] of Object.entries(footprint)) {
      if (!Number.isInteger(value) || value < 1) {
        throw new RangeError(`Invalid footprint ${fieldName} for asset ${assetId}: ${value}`);
      }
    }
  }
}
